# Credit Unions and ATM

In [2]:
import pandas as pd

In [3]:
# Credit Union Branch Information
cu = pd.read_table('/Users/artyom/Documents/work/CreditUnions/call-report-data-2024-12/Credit Union Branch Information.txt', sep=',', encoding='utf-8')

In [4]:
cu

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,SiteId,CU_NAME,SiteName,SiteTypeName,MainOffice,PhysicalAddressLine1,PhysicalAddressLine2,...,MailingAddressCity,MailingAddressStateCode,MailingAddressStateName,MailingAddressPostalCode,PhoneNumber,HoursOfOperation,MemberServices,ATM,DriveThru,Shrd_Serv_Cntr_Net
0,1,12/31/2024 0:00:00,2,45553,MORRIS SHEPPARD TEXARKANA,MORRIS SHEPPARD TEXARKANA FCU,Corporate Office,Yes,419 W 4TH ST,NaN,...,TEXARKANA,TX,Texas,75501,9.037984e+09,"MONDAY - FRIDAY, 8:00 AM - 5:00 PM",1,0,0,0
1,6,12/31/2024 0:00:00,7,40302,THE NEW ORLEANS FIREMEN'S,Slidell,Branch Office,No,1512 Gause Blvd,NaN,...,Metairie,LA,Louisiana,70004,9.856464e+09,M - Th 8am to 4pm Fri 8am to 5pm Sat 9am to 12pm,1,1,1,0
2,6,12/31/2024 0:00:00,7,41260,THE NEW ORLEANS FIREMEN'S,Metairie,Corporate Office,Yes,4401 W Napoleon Ave,NaN,...,Metairie,LA,Louisiana,70004,5.048899e+09,M - Th 8am to 4pm Fri 8am to 5pm Sat 9am to ...,1,0,0,0
3,6,12/31/2024 0:00:00,7,41353,THE NEW ORLEANS FIREMEN'S,Westbank,Branch Office,No,5163 General DeGaulle Dr Ste F,Suite F,...,Metairie,LA,Louisiana,70004,5.043912e+09,M - F 9am to 4pm,1,0,0,0
4,6,12/31/2024 0:00:00,7,41368,THE NEW ORLEANS FIREMEN'S,Mandeville,Branch Office,No,238 Lafitte St,NaN,...,Metairie,LA,Louisiana,70004,9.856243e+09,M - F 9am to 4pm,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22011,97112,12/31/2024 0:00:00,22698,45761,INVESTEX,InvesTex Credit Union,Branch Office,No,230 Cypresswood Dr Ste H,NaN,...,NaN,NaN,NaN,NaN,2.814490e+09,"8:30 to 5:00 Mon,Tues,Wed,Fri 9:00 to 5:00 Thu...",1,1,1,0
22012,97112,12/31/2024 0:00:00,22698,45764,INVESTEX,InvesTex Credit Union,Branch Office,No,5212 Atascocita Rd,NaN,...,NaN,NaN,NaN,NaN,2.814490e+09,"8:30 to 5:00 Mon,Tues,Wed,Fri 9:00 to 5:00 Thu...",1,1,1,0
22013,97112,12/31/2024 0:00:00,22698,45779,INVESTEX,InvesTex Credit Union,Branch Office,No,1614 N Durham Dr,NaN,...,NaN,NaN,NaN,NaN,2.814490e+09,"8:30 to 5:00 Mon,Tues,Wed,Fri 9:00 to 5:00 Thu...",1,1,1,0
22014,97112,12/31/2024 0:00:00,22698,45780,INVESTEX,Investex Credit Union,Corporate Office,Yes,8404 FM 1960 Rd W,NaN,...,Humble,TX,Texas,77338,2.814490e+09,"8:30 to 5:00 Mon, Tues, Wed, Fri9:00 to 5:00 T...",1,1,1,0
22015,97113,12/31/2024 0:00:00,8532,22542,"KH CREDIT UNION, INC.",Paragon Road Branch,Corporate Office,Yes,7740 Paragon Rd,NaN,...,Dayton,OH,Ohio,45459,9.375589e+09,Monday - Friday 8:30 to 4:30,1,1,1,0

In [5]:
cu.columns

Index(['CU_NUMBER', 'CYCLE_DATE', 'JOIN_NUMBER', 'SiteId', 'CU_NAME',
       'SiteName', 'SiteTypeName', 'MainOffice', 'PhysicalAddressLine1',
       'PhysicalAddressLine2', 'PhysicalAddressCity',
       'PhysicalAddressStateCode', 'PhysicalAddressPostalCode',
       'PhysicalAddressCountyName', 'PhysicalAddressCountry',
       'MailingAddressLine1', 'MailingAddressLine2', 'MailingAddressCity',
       'MailingAddressStateCode', 'MailingAddressStateName',
       'MailingAddressPostalCode', 'PhoneNumber', 'HoursOfOperation',
       'MemberServices', 'ATM', 'DriveThru', 'Shrd_Serv_Cntr_Net'],
      dtype='object')

In [8]:
cu.ATM.sum()

16478

In [6]:
cu.CU_NAME.nunique()

4389

In [7]:
cu.CU_NUMBER.nunique()

4545

In [8]:
cu.JOIN_NUMBER.nunique()

4545

In [9]:
cu.groupby("SiteTypeName").size()

SiteTypeName
Branch Office       16783
Corporate Office     5233
dtype: int64

In [13]:
cu.loc[cu.MainOffice == 'Yes']

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,SiteId,CU_NAME,SiteName,SiteTypeName,MainOffice,PhysicalAddressLine1,PhysicalAddressLine2,...,MailingAddressCity,MailingAddressStateCode,MailingAddressStateName,MailingAddressPostalCode,PhoneNumber,HoursOfOperation,MemberServices,ATM,DriveThru,Shrd_Serv_Cntr_Net
0,1,12/31/2024 0:00:00,2,45553,MORRIS SHEPPARD TEXARKANA,MORRIS SHEPPARD TEXARKANA FCU,Corporate Office,Yes,419 W 4TH ST,NaN,...,TEXARKANA,TX,Texas,75501,9.037984e+09,"MONDAY - FRIDAY, 8:00 AM - 5:00 PM",1,0,0,0
2,6,12/31/2024 0:00:00,7,41260,THE NEW ORLEANS FIREMEN'S,Metairie,Corporate Office,Yes,4401 W Napoleon Ave,NaN,...,Metairie,LA,Louisiana,70004,5.048899e+09,M - Th 8am to 4pm Fri 8am to 5pm Sat 9am to ...,1,0,0,0
11,12,12/31/2024 0:00:00,11,46813,FRANKLIN TRUST,Corporate Office,Corporate Office,Yes,624 Franklin Ave,NaN,...,Hartford,CT,Connecticut,06114,8.602964e+09,M-F 7:30 am- 5pm,0,0,0,0
22,13,12/31/2024 0:00:00,12,51081,EFCU FINANCIAL,Sherwood - Future Ops Center,Corporate Office,Yes,3232 S Sherwood Forest Blvd,NaN,...,Baton Rouge,LA,Louisiana,70816-2218,2.252147e+09,8:00am - 5:00pm,0,0,0,0
23,16,12/31/2024 0:00:00,14,33420,WOODMEN,Woodmen Federal Credit Union,Corporate Office,Yes,1700 FARNAM ST STE 1000,NaN,...,OMAHA,NE,Nebraska,68102,4.022717e+09,8:30-4:00,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21991,97109,12/31/2024 0:00:00,2759,34385,RIVER VALLEY,Main Office Corporate Headquarters,Corporate Office,Yes,505 Earl Blvd,NaN,...,Miamisburg,OH,Ohio,45342,9.378596e+09,8:00am - 5:00pm M-F,0,0,0,0
21998,97110,12/31/2024 0:00:00,17502,26296,ROCKY MOUNTAIN,North Montana,Corporate Office,Yes,3400 N Montana Ave,NaN,...,Helena,MT,Montana,59602,4.064493e+09,M-F 8:30 am - 5:30 pm,1,1,1,0
22005,97111,12/31/2024 0:00:00,21049,26729,ABBEY,Abbey Credit Union,Corporate Office,Yes,800 Falls Creek Dr,NaN,...,Vandalia,OH,Ohio,45377,9.378988e+09,Monday through Thursday 9:00 - 5:00 Friday: 9:...,1,1,1,1
22014,97112,12/31/2024 0:00:00,22698,45780,INVESTEX,Investex Credit Union,Corporate Office,Yes,8404 FM 1960 Rd W,NaN,...,Humble,TX,Texas,77338,2.814490e+09,"8:30 to 5:00 Mon, Tues, Wed, Fri9:00 to 5:00 T...",1,1,1,0
22015,97113,12/31/2024 0:00:00,8532,22542,"KH CREDIT UNION, INC.",Paragon Road Branch,Corporate Office,Yes,7740 Paragon Rd,NaN,...,Dayton,OH,Ohio,45459,9.375589e+09,Monday - Friday 8:30 to 4:30,1,1,1,0

In [10]:
duplicates = cu.duplicated()
duplicates.sum()

0

In [11]:
# ATM location data
atm = pd.read_table('/Users/artyom/Documents/work/CreditUnions/call-report-data-2024-12/ATM Locations.txt', sep=',', encoding='latin1')
atm

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,CU_NAME,SiteId,SiteName,SiteTypeName,SiteFunctionName,PhysicalAddressLine1,PhysicalAddressLine2,PhysicalAddressCity,PhysicalAddressStateCode,PhysicalAddressStateName,PhysicalAddressPostalCode,PhysicalAddressCountyName,PhysicalAddressCountry
0,6,12/31/2024 0:00:00,7,THE NEW ORLEANS FIREMEN'S,40302,Slidell,Branch Office,ATM,1512 Gause Blvd,NaN,Slidell,LA,Louisiana,70458,Saint Tammany,United States
1,6,12/31/2024 0:00:00,7,THE NEW ORLEANS FIREMEN'S,41368,Mandeville,Branch Office,ATM,238 Lafitte St,NaN,Mandeville,LA,Louisiana,70448,Saint Tammany,United States
2,6,12/31/2024 0:00:00,7,THE NEW ORLEANS FIREMEN'S,41400,St. James,Branch Office,ATM,1901 Highway 3125,NaN,Lutcher,LA,Louisiana,70071-5633,Saint James,United States
3,6,12/31/2024 0:00:00,7,THE NEW ORLEANS FIREMEN'S,41419,Lockport,Branch Office,ATM,400 Crescent Ave,NaN,Lockport,LA,Louisiana,70374,Lafourche,United States
4,6,12/31/2024 0:00:00,7,THE NEW ORLEANS FIREMEN'S,51676,West Jefferson,Branch Office,ATM,1111 Medical Center Blvd,Ste 118 N,Marrero,LA,Louisiana,70072,Jefferson,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17551,97113,12/31/2024 0:00:00,8532,"KH CREDIT UNION, INC.",51850,Fort Hamilton Hospital,Other,ATM,630 Eaton Ave,NaN,Hamilton,OH,Ohio,45013,Butler,United States
17552,97113,12/31/2024 0:00:00,8532,"KH CREDIT UNION, INC.",51851,Beavercreek Soin ATM,Other,ATM,3535 Pentagon Blvd,NaN,Beavercreek,OH,Ohio,45431-1705,Greene,United States
17553,97113,12/31/2024 0:00:00,8532,"KH CREDIT UNION, INC.",51852,Prestige Plaza ATM,Other,ATM,1 Prestige Plaza Dr,NaN,Miamisburg,OH,Ohio,45342,Montgomery,United States
17554,97113,12/31/2024 0:00:00,8532,"KH CREDIT UNION, INC.",51853,Cancer Center ATM,Other,ATM,3700 Southern Blvd,NaN,Kettering,OH,Ohio,45429,Montgomery,United States
17555,97113,12/31/2024 0:00:00,8532,"KH CREDIT UNION, INC.",51854,Troy ATM,Other,ATM,600 W Main St,NaN,Troy,OH,Ohio,45373,Miami,United States

In [12]:
atm.groupby("SiteTypeName").size()

SiteTypeName
Branch Office       14338
Corporate Office     2247
Other                 971
dtype: int64

In [13]:
cu.loc[cu.CU_NAME	== "THE NEW ORLEANS FIREMEN'S"]

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,SiteId,CU_NAME,SiteName,SiteTypeName,MainOffice,PhysicalAddressLine1,PhysicalAddressLine2,...,MailingAddressCity,MailingAddressStateCode,MailingAddressStateName,MailingAddressPostalCode,PhoneNumber,HoursOfOperation,MemberServices,ATM,DriveThru,Shrd_Serv_Cntr_Net
1,6,12/31/2024 0:00:00,7,40302,THE NEW ORLEANS FIREMEN'S,Slidell,Branch Office,No,1512 Gause Blvd,NaN,...,Metairie,LA,Louisiana,70004,9.856464e+09,M - Th 8am to 4pm Fri 8am to 5pm Sat 9am to 12pm,1,1,1,0
2,6,12/31/2024 0:00:00,7,41260,THE NEW ORLEANS FIREMEN'S,Metairie,Corporate Office,Yes,4401 W Napoleon Ave,NaN,...,Metairie,LA,Louisiana,70004,5.048899e+09,M - Th 8am to 4pm Fri 8am to 5pm Sat 9am to ...,1,0,0,0
3,6,12/31/2024 0:00:00,7,41353,THE NEW ORLEANS FIREMEN'S,Westbank,Branch Office,No,5163 General DeGaulle Dr Ste F,Suite F,...,Metairie,LA,Louisiana,70004,5.043912e+09,M - F 9am to 4pm,1,0,0,0
4,6,12/31/2024 0:00:00,7,41368,THE NEW ORLEANS FIREMEN'S,Mandeville,Branch Office,No,238 Lafitte St,NaN,...,Metairie,LA,Louisiana,70004,9.856243e+09,M - F 9am to 4pm,1,1,0,0
5,6,12/31/2024 0:00:00,7,41384,THE NEW ORLEANS FIREMEN'S,New Orleans,Branch Office,No,3840 Canal St,Suite 3,...,Metairie,LA,Louisiana,70004,5.048897e+09,M - F 9am to 4pm,1,0,0,0
6,6,12/31/2024 0:00:00,7,41400,THE NEW ORLEANS FIREMEN'S,St. James,Branch Office,No,1901 Highway 3125,NaN,...,Metairie,LA,Louisiana,70004,2.258694e+09,M - Th 8am to 4pm Fri 8am to 5pm Sat 9am to...,1,1,1,0
7,6,12/31/2024 0:00:00,7,41413,THE NEW ORLEANS FIREMEN'S,Picayune,Branch Office,No,1620 Goodyear Blvd Ste C,NaN,...,Metairie,LA,Louisiana,70004,5.048897e+09,M - F 9am to 4pm,1,0,0,0
8,6,12/31/2024 0:00:00,7,41419,THE NEW ORLEANS FIREMEN'S,Lockport,Branch Office,No,400 Crescent Ave,NaN,...,Metairie,LA,Louisiana,70004,9.855321e+09,M - F 9am to 4pm,1,1,0,0
9,6,12/31/2024 0:00:00,7,51675,THE NEW ORLEANS FIREMEN'S,Bogalusa,Branch Office,No,205 Arkansas Ave,NaN,...,Metairie,LA,Louisiana,70004,5.048899e+09,M - F 9am to 4pm,1,0,0,0
10,6,12/31/2024 0:00:00,7,51676,THE NEW ORLEANS FIREMEN'S,West Jefferson,Branch Office,No,1111 Medical Center Blvd,Ste 118 N,...,Marrero,LA,Louisiana,70072,5.048899e+09,M - F 7am to 3:30pm,1,1,0,0

In [14]:
atm.columns

Index(['CU_NUMBER', 'CYCLE_DATE', 'JOIN_NUMBER', 'CU_NAME', 'SiteId',
       'SiteName', 'SiteTypeName', 'SiteFunctionName', 'PhysicalAddressLine1',
       'PhysicalAddressLine2', 'PhysicalAddressCity',
       'PhysicalAddressStateCode', 'PhysicalAddressStateName',
       'PhysicalAddressPostalCode', 'PhysicalAddressCountyName',
       'PhysicalAddressCountry'],
      dtype='object')

In [15]:
cu.columns

Index(['CU_NUMBER', 'CYCLE_DATE', 'JOIN_NUMBER', 'SiteId', 'CU_NAME',
       'SiteName', 'SiteTypeName', 'MainOffice', 'PhysicalAddressLine1',
       'PhysicalAddressLine2', 'PhysicalAddressCity',
       'PhysicalAddressStateCode', 'PhysicalAddressPostalCode',
       'PhysicalAddressCountyName', 'PhysicalAddressCountry',
       'MailingAddressLine1', 'MailingAddressLine2', 'MailingAddressCity',
       'MailingAddressStateCode', 'MailingAddressStateName',
       'MailingAddressPostalCode', 'PhoneNumber', 'HoursOfOperation',
       'MemberServices', 'ATM', 'DriveThru', 'Shrd_Serv_Cntr_Net'],
      dtype='object')

In [16]:
# Check whether two Identifiers are unique
atm.CU_NUMBER.nunique() == atm.JOIN_NUMBER.nunique()

True

In [17]:
# We will join only the locations from the ATM file that are not already in the CU file

atm = atm.loc[atm.SiteTypeName == "Other"]

In [18]:
locations = pd.merge(cu, atm, how='outer')

In [19]:
cu.shape[0] + atm.shape[0] - locations.shape[0]

0

In [20]:
locations.SiteTypeName.value_counts()

SiteTypeName
Branch Office       16783
Corporate Office     5233
Other                 971
Name: count, dtype: int64

In [21]:
locations.iloc[:, 6:20].tail(20)

,SiteTypeName,MainOffice,PhysicalAddressLine1,PhysicalAddressLine2,PhysicalAddressCity,PhysicalAddressStateCode,PhysicalAddressPostalCode,PhysicalAddressCountyName,PhysicalAddressCountry,MailingAddressLine1,MailingAddressLine2,MailingAddressCity,MailingAddressStateCode,MailingAddressStateName
22967,Branch Office,No,5129 S County Road 25A,NaN,Tipp City,OH,45371,Miami,United States,800 Falls Creek Dr,NaN,Vandalia,OH,Ohio
22968,Branch Office,No,905 Aldine Bender Rd,NaN,Houston,TX,77032,Harris,United States,905 Aldine Bender Rd,NaN,Houston,TX,Texas
22969,Branch Office,No,24922 State Highway 249,NaN,Tomball,TX,77375,Harris,United States,NaN,NaN,NaN,NaN,NaN
22970,Branch Office,No,230 Cypresswood Dr Ste H,NaN,Spring,TX,77388,Harris,United States,NaN,NaN,NaN,NaN,NaN
22971,Branch Office,No,5212 Atascocita Rd,NaN,Humble,TX,77346,Harris,United States,NaN,NaN,NaN,NaN,NaN
22972,Branch Office,No,1614 N Durham Dr,NaN,Houston,TX,77008,Harris,United States,NaN,NaN,NaN,NaN,NaN
22973,Corporate Office,Yes,8404 FM 1960 Rd W,NaN,Humble,TX,77338,Harris,United States,8404 FM 1960 Rd W,NaN,Humble,TX,Texas
22974,Corporate Office,Yes,7740 Paragon Rd,NaN,Dayton,OH,45459,Montgomery,United States,7740 Paragon Rd,NaN,Dayton,OH,Ohio
22975,Other,NaN,3535 Southern Blvd,NaN,Kettering,OH,45429,Montgomery,United States,NaN,NaN,NaN,NaN,NaN
22976,Other,NaN,405 W Grand Ave,NaN,Dayton,OH,45405-7538,Montgomery,United States,NaN,NaN,NaN,NaN,NaN
22977,Other,NaN,4000 Miamisburg Centerville Rd,NaN,Miamisburg,OH,45342-7615,Montgomery,United States,NaN,NaN,NaN,NaN,NaN
22978,Other,NaN,1141 N Monroe Dr,NaN,Xenia,OH,45385-1619,Greene,United States,NaN,NaN,NaN,NaN,NaN
22979,Other,NaN,8701 Old Troy Pike,NaN,Huber Heights,OH,45424-1066,Montgomery,United States,NaN,NaN,NaN,NaN,NaN
22980,Other,NaN,1997 Miamisburg Centerville Rd,NaN,Dayton,OH,45459-3811,Montgomery,United States,NaN,NaN,NaN,NaN,NaN
22981,Other,NaN,2150 Leiter Rd,NaN,Miamisburg,OH,45342-3809,Montgomery,United States,NaN,NaN,NaN,NaN,NaN
22982,Other,NaN,630 Eaton Ave,NaN,Hamilton,OH,45013,Butler,United States,NaN,NaN,NaN,NaN,NaN
22983,Other,NaN,3535 Pentagon Blvd,NaN,Beavercreek,OH,45431-1705,Greene,United States,NaN,NaN,NaN,NaN,NaN
22984,Other,NaN,1 Prestige Plaza Dr,NaN,Miamisburg,OH,45342,Montgomery,United States,NaN,NaN,NaN,NaN,NaN
22985,Other,NaN,3700 Southern Blvd,NaN,Kettering,OH,45429,Montgomery,United States,NaN,NaN,NaN,NaN,NaN
22986,Other,NaN,600 W Main St,NaN,Troy,OH,45373,Miami,United States,NaN,NaN,NaN,NaN,NaN

# Financial variables

In [22]:
foicu = pd.read_table('/Users/artyom/Documents/work/CreditUnions/call-report-data-2024-12/FOICU.txt', sep=',', encoding='latin1')
foicu

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,RSSD,CU_TYPE,CU_NAME,CITY,STATE,CharterState,STATE_CODE,...,SE,DISTRICT,YEAR_OPENED,TOM_CODE,LIMITED_INC,ISSUE_DATE,Peer_Group,Quarter_Flag,IsMDI,INSURED_DATE
0,1,12/31/2024 0:00:00,2,50377.0,1,MORRIS SHEPPARD TEXARKANA,TEXARKANA,TX,TX,48,...,J,8,1934,36,1,1/1/1934 0:00:00,3,0,False,1/4/1971 0:00:00
1,6,12/31/2024 0:00:00,7,54571.0,1,THE NEW ORLEANS FIREMEN'S,Metairie,LA,LA,22,...,I,5,1934,36,1,1/1/1934 0:00:00,5,0,False,1/4/1971 0:00:00
2,12,12/31/2024 0:00:00,11,56678.0,1,FRANKLIN TRUST,Hartford,CT,CT,9,...,A,6,1934,0,1,1/1/1934 0:00:00,4,0,False,10/29/1971 0:00:00
3,13,12/31/2024 0:00:00,12,861676.0,1,EFCU FINANCIAL,BATON ROUGE,LA,LA,22,...,I,6,1934,0,1,1/1/1934 0:00:00,6,0,False,1/4/1971 0:00:00
4,16,12/31/2024 0:00:00,14,59277.0,1,WOODMEN,OMAHA,NE,NE,31,...,D,8,1934,50,0,1/1/1934 0:00:00,2,0,False,4/26/1971 0:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4545,97109,12/31/2024 0:00:00,2759,825285.0,3,RIVER VALLEY,Miamisburg,OH,OH,39,...,Z,99,1949,99,1,6/10/1949 0:00:00,5,0,False,1/4/1971 0:00:00
4546,97110,12/31/2024 0:00:00,17502,492892.0,3,ROCKY MOUNTAIN,Helena,MT,MT,30,...,Q,1,1940,99,0,1/1/1940 0:00:00,5,0,False,2/2/1976 0:00:00
4547,97111,12/31/2024 0:00:00,21049,774598.0,3,ABBEY,Vandalia,OH,OH,39,...,Z,99,1937,99,1,11/11/1937 0:00:00,5,0,False,3/11/1986 0:00:00
4548,97112,12/31/2024 0:00:00,22698,851695.0,3,INVESTEX,Humble,TX,TX,48,...,E,10,1952,99,0,11/5/1952 0:00:00,5,0,False,7/10/1991 0:00:00
4549,97113,12/31/2024 0:00:00,8532,868488.0,3,"KH CREDIT UNION, INC.",Dayton,OH,OH,39,...,O,6,1964,99,0,6/16/1964 0:00:00,4,0,False,8/20/1971 0:00:00

In [23]:
foicu.columns

Index(['CU_NUMBER', 'CYCLE_DATE', 'JOIN_NUMBER', 'RSSD', 'CU_TYPE', 'CU_NAME',
       'CITY', 'STATE', 'CharterState', 'STATE_CODE', 'ZIP_CODE',
       'COUNTY_CODE', 'CONG_DIST', 'SMSA', 'ATTENTION_OF', 'STREET', 'REGION',
       'SE', 'DISTRICT', 'YEAR_OPENED', 'TOM_CODE', 'LIMITED_INC',
       'ISSUE_DATE', 'Peer_Group', 'Quarter_Flag', 'IsMDI', 'INSURED_DATE'],
      dtype='object')

In [24]:
#"IsMDI","Field size of 1 Character Max.;The credit union IsMDI (Minority Depository Institution) code.
foicu.IsMDI.value_counts()

IsMDI
False    4128
True      422
Name: count, dtype: int64

In [25]:
foicu.CU_NUMBER.nunique() == foicu.JOIN_NUMBER.nunique()

True

In [26]:
locations_f = pd.merge(locations, foicu[["JOIN_NUMBER", "YEAR_OPENED", "TOM_CODE", "IsMDI"]], on="JOIN_NUMBER", how="left")

In [27]:
locations_f

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,SiteId,CU_NAME,SiteName,SiteTypeName,MainOffice,PhysicalAddressLine1,PhysicalAddressLine2,...,HoursOfOperation,MemberServices,ATM,DriveThru,Shrd_Serv_Cntr_Net,SiteFunctionName,PhysicalAddressStateName,YEAR_OPENED,TOM_CODE,IsMDI
0,1,12/31/2024 0:00:00,2,45553,MORRIS SHEPPARD TEXARKANA,MORRIS SHEPPARD TEXARKANA FCU,Corporate Office,Yes,419 W 4TH ST,NaN,...,"MONDAY - FRIDAY, 8:00 AM - 5:00 PM",1.0,0.0,0.0,0.0,NaN,NaN,1934,36,False
1,6,12/31/2024 0:00:00,7,40302,THE NEW ORLEANS FIREMEN'S,Slidell,Branch Office,No,1512 Gause Blvd,NaN,...,M - Th 8am to 4pm Fri 8am to 5pm Sat 9am to 12pm,1.0,1.0,1.0,0.0,NaN,NaN,1934,36,False
2,6,12/31/2024 0:00:00,7,41260,THE NEW ORLEANS FIREMEN'S,Metairie,Corporate Office,Yes,4401 W Napoleon Ave,NaN,...,M - Th 8am to 4pm Fri 8am to 5pm Sat 9am to ...,1.0,0.0,0.0,0.0,NaN,NaN,1934,36,False
3,6,12/31/2024 0:00:00,7,41353,THE NEW ORLEANS FIREMEN'S,Westbank,Branch Office,No,5163 General DeGaulle Dr Ste F,Suite F,...,M - F 9am to 4pm,1.0,0.0,0.0,0.0,NaN,NaN,1934,36,False
4,6,12/31/2024 0:00:00,7,41368,THE NEW ORLEANS FIREMEN'S,Mandeville,Branch Office,No,238 Lafitte St,NaN,...,M - F 9am to 4pm,1.0,1.0,0.0,0.0,NaN,NaN,1934,36,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22982,97113,12/31/2024 0:00:00,8532,51850,"KH CREDIT UNION, INC.",Fort Hamilton Hospital,Other,NaN,630 Eaton Ave,NaN,...,NaN,NaN,NaN,NaN,NaN,ATM,Ohio,1964,99,False
22983,97113,12/31/2024 0:00:00,8532,51851,"KH CREDIT UNION, INC.",Beavercreek Soin ATM,Other,NaN,3535 Pentagon Blvd,NaN,...,NaN,NaN,NaN,NaN,NaN,ATM,Ohio,1964,99,False
22984,97113,12/31/2024 0:00:00,8532,51852,"KH CREDIT UNION, INC.",Prestige Plaza ATM,Other,NaN,1 Prestige Plaza Dr,NaN,...,NaN,NaN,NaN,NaN,NaN,ATM,Ohio,1964,99,False
22985,97113,12/31/2024 0:00:00,8532,51853,"KH CREDIT UNION, INC.",Cancer Center ATM,Other,NaN,3700 Southern Blvd,NaN,...,NaN,NaN,NaN,NaN,NaN,ATM,Ohio,1964,99,False
22986,97113,12/31/2024 0:00:00,8532,51854,"KH CREDIT UNION, INC.",Troy ATM,Other,NaN,600 W Main St,NaN,...,NaN,NaN,NaN,NaN,NaN,ATM,Ohio,1964,99,False

In [28]:
locations_f.CU_NUMBER.nunique()

4545

# Joining Financial Data

In [29]:
names = pd.read_table('/Users/artyom/Documents/work/CreditUnions/call-report-data-2024-12/AcctDesc.txt', sep=',', encoding='latin1')
fs220 = pd.read_table('/Users/artyom/Documents/work/CreditUnions/call-report-data-2024-12/FS220.txt', sep=',', encoding='latin1')
fs220s = pd.read_table('/Users/artyom/Documents/work/CreditUnions/call-report-data-2024-12/FS220S.txt', sep=',', encoding='latin1')
fs220a = pd.read_table('/Users/artyom/Documents/work/CreditUnions/call-report-data-2024-12/FS220A.txt', sep=',', encoding='latin1')
fs220d = pd.read_table('/Users/artyom/Documents/work/CreditUnions/call-report-data-2024-12/FS220D.txt', sep=',', encoding='latin1')
fs220c = pd.read_table('/Users/artyom/Documents/work/CreditUnions/call-report-data-2024-12/FS220C.txt', sep=',', encoding='latin1')

In [30]:
for i in fs220s.columns:
   print(i)

CU_NUMBER
CYCLE_DATE
JOIN_NUMBER
ACCT_PG0001
ACCT_PP0037
ACCT_PP0038
ACCT_PP0039
ACCT_PP0040
ACCT_PP0041
ACCT_PP0042
ACCT_PP0043
ACCT_PP0044
ACCT_PP0045
ACCT_PP0046
ACCT_PP0047
ACCT_PP0048
ACCT_PR0001
ACCT_PR0002
ACCT_PR0003
ACCT_PR0004
BoardAsianAmerican
BoardBlackAmerican
BoardHispanicAmerican
BoardMinorityStatus
BoardNativeAmerican
CurMemAsianAmerican
CurMemBlackAmerican
CurMemHispanicAmerican
CurMemMinorityStatus
CurMemNativeAmerican
EligibleMinorityStatus
FOMAsianAmerican
FOMBlackAmerican
FOMHispanicAmerican
FOMMinorityStatus
FOMNativeAmerican
MemberMinorityStatus

In [31]:
fs220d.JOIN_NUMBER.nunique() == fs220d.CU_NUMBER.nunique()

True

In [32]:
merged_fs220 = fs220.merge(fs220s.drop(columns=['CYCLE_DATE', 'CU_NUMBER']), on='JOIN_NUMBER', how='outer') \
                    .merge(fs220a.drop(columns=['CYCLE_DATE', 'CU_NUMBER']), on='JOIN_NUMBER', how='outer') \
                    .merge(fs220d.drop(columns=['CYCLE_DATE', 'CU_NUMBER']), on='JOIN_NUMBER', how='outer') \
                    .merge(fs220c.drop(columns=['CYCLE_DATE', 'CU_NUMBER']), on='JOIN_NUMBER', how='outer')

# Display the merged dataframe
merged_fs220

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,UPDATE_DATE,ACCT_007,ACCT_008,ACCT_009,ACCT_010,ACCT_011C,ACCT_013,...,ACCT_038B,ACCT_038C,ACCT_038D,ACCT_038E,ACCT_039A,ACCT_039B,ACCT_039C,ACCT_039D,ACCT_039E,ACCT_642
0,1,12/31/2024 0:00:00,2,1/29/2025 10:45:12 PM,41785,5201,0,11835153,0,10456209,...,0,0,0,0,0,0,0,0,0,0
1,6,12/31/2024 0:00:00,7,1/30/2025 10:36:36 PM,2868178,750856,0,269952063,0,204597639,...,0,0,0,0,0,0,0,0,0,0
2,12,12/31/2024 0:00:00,11,1/23/2025 10:14:11 PM,4871838,488776,0,60540924,0,55308291,...,0,0,0,0,0,0,0,0,0,0
3,13,12/31/2024 0:00:00,12,1/29/2025 10:16:22 PM,18140884,2568776,0,1166537765,0,930699777,...,0,0,0,0,0,0,0,0,0,0
4,16,12/31/2024 0:00:00,14,1/16/2025 10:09:26 PM,0,2147,0,9364728,0,8039127,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4545,24958,12/31/2024 0:00:00,26474,1/27/2025 10:26:42 PM,0,13253,0,2574318,0,1196783,...,0,0,0,0,0,0,0,0,0,0
4546,68740,12/31/2024 0:00:00,26475,1/31/2025 10:01:16 PM,0,2877,0,1092983,0,76,...,0,0,0,0,0,0,0,0,0,0
4547,24960,12/31/2024 0:00:00,26476,1/22/2025 10:06:09 PM,0,0,0,289005,0,0,...,0,0,0,0,0,0,0,0,0,0
4548,24961,12/31/2024 0:00:00,26477,2/6/2025 10:03:02 PM,0,0,0,1990,0,0,...,0,0,0,0,0,0,0,0,0,0
4549,24968,12/31/2024 0:00:00,26478,2/5/2025 10:00:57 PM,0,0,0,350000,0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
for i in merged_fs220.columns:
    print(i)

CU_NUMBER
CYCLE_DATE
JOIN_NUMBER
UPDATE_DATE
ACCT_007
ACCT_008
ACCT_009
ACCT_010
ACCT_011C
ACCT_013
ACCT_018
ACCT_019
ACCT_021B
ACCT_022B
ACCT_023B
ACCT_025A
ACCT_025B
ACCT_031A
ACCT_031B
ACCT_041B
ACCT_042
ACCT_058C
ACCT_065
ACCT_067
ACCT_068
ACCT_069
ACCT_080
ACCT_083
ACCT_084
ACCT_100
ACCT_300
ACCT_340
ACCT_380
ACCT_386
ACCT_387
ACCT_388
ACCT_392
ACCT_400
ACCT_457
ACCT_521
ACCT_522
ACCT_523
ACCT_524
ACCT_550
ACCT_551
ACCT_552
ACCT_562
ACCT_563
ACCT_602
ACCT_630
ACCT_652A
ACCT_652B1
ACCT_652B2
ACCT_655A
ACCT_655B1
ACCT_655B2
ACCT_656C
ACCT_657
ACCT_658
ACCT_662
ACCT_668
ACCT_671
ACCT_672A
ACCT_672B1
ACCT_672B2
ACCT_703
ACCT_704
ACCT_705
ACCT_706
ACCT_707
ACCT_708
ACCT_710
ACCT_712
ACCT_713
ACCT_714
ACCT_715
ACCT_716
ACCT_718
ACCT_719
ACCT_720
ACCT_721
ACCT_722
ACCT_723
ACCT_724
ACCT_730
ACCT_741A
ACCT_741B1
ACCT_741B2
ACCT_742A
ACCT_742B1
ACCT_742B2
ACCT_746A
ACCT_746B1
ACCT_746B2
ACCT_749
ACCT_750A
ACCT_750B1
ACCT_750B2
ACCT_751
ACCT_755
ACCT_760C
ACCT_761C
ACCT_771
ACCT_775
ACCT_794
ACCT_798
ACCT_799A
ACCT_799B1
ACCT_799B2
ACCT_825
ACCT_860C
ACCT_880
ACCT_902
ACCT_906A
ACCT_908A
ACCT_908C
ACCT_911
ACCT_931
ACCT_940
ACCT_959
ACCT_960
ACCT_968
ACCT_973
ACCT_975
ACCT_976
ACCT_991
Acct_965A
Acct_965B
Acct_965C
Acct_965D
ACCT_020A
ACCT_020B
ACCT_024A
ACCT_024B
ACCT_042A
ACCT_090A
ACCT_090B
ACCT_090C
ACCT_090D
ACCT_099A
ACCT_143A
ACCT_143B
ACCT_143C
ACCT_143D
ACCT_400A
ACCT_400B
ACCT_400C
ACCT_400D
ACCT_400F
ACCT_459A
ACCT_463A
ACCT_475A
ACCT_475B
ACCT_475C
ACCT_475D
ACCT_691B
ACCT_691C
ACCT_692
ACCT_692A
ACCT_704A
ACCT_704B
ACCT_704C
ACCT_704D
ACCT_704E
ACCT_705A
ACCT_705B
ACCT_708B
ACCT_720A
ACCT_720B
ACCT_720C
ACCT_720D
ACCT_720E
ACCT_721A
ACCT_721B
ACCT_724B
ACCT_733A
ACCT_745C1
ACCT_745C2
ACCT_796C1
ACCT_796C2
ACCT_797C1
ACCT_797C2
ACCT_799C1
ACCT_799C2
ACCT_965C1
ACCT_965C2
ACCT_088
ACCT_799A1
ACCT_672B
ACCT_672C1
ACCT_672C2
ACCT_672D
ACCT_744B
ACCT_744C1
ACCT_744C2
ACCT_744D
ACCT_652B
ACCT_652C1
ACCT_652C2
ACCT_652D
ACCT_766A
ACCT_766B
ACCT_766C1
ACCT_766C2
ACCT_766D
ACCT_766E
ACCT_798A1
ACCT_798A2
ACCT_798A3
ACCT_009A
ACCT_009B
ACCT_009C
ACCT_769A1
ACCT_769B1
ACCT_616
ACCT_616A
ACCT_704A1
ACCT_704C1
ACCT_980
ACCT_742C1
ACCT_742C2
ACCT_020J
ACCT_020K
ACCT_020L
ACCT_021J
ACCT_021K
ACCT_021L
ACCT_022J
ACCT_022K
ACCT_022L
ACCT_023J
ACCT_023K
ACCT_023L
ACCT_041J
ACCT_041K
ACCT_041L
Acct_1019
Acct_1019A
Acct_1019B
Acct_1019C
Acct_1019D
Acct_1019E
Acct_789A
Acct_789A1
Acct_789B
Acct_789B1
ACCT_PG0001
ACCT_PP0037
ACCT_PP0038
ACCT_PP0039
ACCT_PP0040
ACCT_PP0041
ACCT_PP0042
ACCT_PP0043
ACCT_PP0044
ACCT_PP0045
ACCT_PP0046
ACCT_PP0047
ACCT_PP0048
ACCT_PR0001
ACCT_PR0002
ACCT_PR0003
ACCT_PR0004
BoardAsianAmerican
BoardBlackAmerican
BoardHispanicAmerican
BoardMinorityStatus
BoardNativeAmerican
CurMemAsianAmerican
CurMemBlackAmerican
CurMemHispanicAmerican
CurMemMinorityStatus
CurMemNativeAmerican
EligibleMinorityStatus_x
FOMAsianAmerican
FOMBlackAmerican
FOMHispanicAmerican
FOMMinorityStatus
FOMNativeAmerican
MemberMinorityStatus_x
ACCT_001
ACCT_011A
ACCT_011B1
ACCT_011B2
ACCT_013A
ACCT_013B1
ACCT_013B2
ACCT_014
ACCT_017
ACCT_018A
ACCT_018B1
ACCT_018B2
ACCT_021A
ACCT_022A
ACCT_023A
ACCT_041A
ACCT_058A
ACCT_058B1
ACCT_058B2
ACCT_062
ACCT_063
ACCT_076
ACCT_077
ACCT_078
ACCT_079
ACCT_081
ACCT_082
ACCT_090
ACCT_099
ACCT_110
ACCT_119
ACCT_120
ACCT_124
ACCT_125A
ACCT_125B
ACCT_125C
ACCT_125D
ACCT_125E
ACCT_126A
ACCT_126B
ACCT_126C
ACCT_126D
ACCT_126E
ACCT_131
ACCT_132
ACCT_133
ACCT_134
ACCT_135
ACCT_140
ACCT_142
ACCT_143
ACCT_144
ACCT_210
ACCT_230
ACCT_250
ACCT_260
ACCT_270
ACCT_280
ACCT_290
ACCT_305
ACCT_310
ACCT_314
ACCT_315
ACCT_320
ACCT_360
ACCT_370
ACCT_381
ACCT_384
ACCT_385
ACCT_389
ACCT_391
ACCT_393
ACCT_395
ACCT_396
ACCT_397
ACCT_399
ACCT_420
ACCT_430
ACCT_440
ACCT_451
ACCT_452
ACCT_453
ACCT_454
ACCT_455
ACCT_458
ACCT_460
ACCT_463
ACCT_475
ACCT_481
ACCT_482
ACCT_532
ACCT_547
ACCT_548
ACCT_549
ACCT_553
ACCT_554
ACCT_555
ACCT_560
ACCT_561
ACCT_564A
ACCT_564B
ACCT_593
ACCT_594
ACCT_595
ACCT_596
ACCT_599
ACCT_002
ACCT_115
ACCT_116
ACCT_117
ACCT_350
ACCT_565
Acct_661A
Acct_769A
Acct_769B
Acct_820A
Acct_954
Acct_925A
Acct_925B1
Acct_925B2
Acct_010A
Acct_010B
Acct_010C
Acct_730A
Acct_730B
Acct_730C
Acct_799I
Acct_814A
Acct_889A
Acct_889B
Acct_892A
Acct_892B
Acct_945A
Acct_945B
Acct_996
Acct_997
Acct_998
Acct_999
ACCT_779A
ACCT_785A
ACCT_798A
ACCT_814B
ACCT_865A
ACCT_900A
ACCT_900B
ACCT_900C
ACCT_900D
ACCT_900F
ACCT_903
ACCT_904
ACCT_905
ACCT_906
ACCT_961A
ACCT_972A
ACCT_972B
ACCT_972C
ACCT_972D
ACCT_972E
ACCT_973A
ACCT_973B
ACCT_976B
ACCT_982A
ACCT_982B
ACCT_982C
ACCT_982D
ACCT_982E
ACCT_983A
ACCT_983B
ACCT_986B
ACCT_617A
ACCT_618A
ACCT_718A
ACCT_617B
ACCT_617C
ACCT_618B
ACCT_618C
ACCT_883A
ACCT_883B1
ACCT_883B2
ACCT_883C
ACCT_881
ACCT_882
ACCT_822
ACCT_567
ACCT_568
ACCT_020C
ACCT_021C
ACCT_022C
ACCT_023C
ACCT_041C
ACCT_020D
ACCT_021D
ACCT_022D
ACCT_023D
ACCT_041D
ACCT_713A
ACCT_714A
ACCT_715A
ACCT_716A
ACCT_020E
ACCT_021E
ACCT_022E
ACCT_023E
ACCT_041E
ACCT_020F
ACCT_021F
ACCT_022F
ACCT_023F
ACCT_041F
ACCT_065A
ACCT_065B
ACCT_065C
ACCT_065D
ACCT_065E
ACCT_067A
ACCT_067B
ACCT_067C
ACCT_550J
ACCT_550K
ACCT_550L
ACCT_551J
ACCT_551K
ACCT_551L
ACCT_029A
ACCT_029B
ACCT_029C
ACCT_029D
ACCT_029E
ACCT_030A
ACCT_030B
ACCT_030C
ACCT_030D
ACCT_030E
ACCT_032A
ACCT_032B
ACCT_032C
ACCT_032D
ACCT_032E
ACCT_704F1
ACCT_704F2
ACCT_704F3
ACCT_704F4
ACCT_811B
ACCT_PP0027
ACCT_PP0029
ACCT_PP0031
CEO
Fax
Phone
Preparer
President
Principal
ACCT_876
ACCT_830A
ACCT_830B
ACCT_830C
ACCT_830D
ACCT_830E
ACCT_830F
ACCT_830G
ACCT_830H
ACCT_830I
ACCT_830J
CEO_F
CEO_M
Preparer_F
Preparer_M
President_F
President_M
Principal_F
Principal_M
Acct_891
ACCT_893
ACCT_894
Acct_700
Acct_701
Acct_886A
Acct_886B
Acct_886C
Acct_886D
Acct_886E
Acct_886F
Acct_886G
Acct_887A
Acct_887B
Acct_887C
Acct_887D
Acct_887E
Acct_887F
Acct_887G
Acct_887H
Acct_887I
Acct_887J
Acct_887K
Acct_887L
Acct_889
Acct_711
Acct_887M
Acct_887N
Acct_887P
Acct_887Z
Acct_842
Acct_843
ACCT_830K
ACCT_830L
ACCT_830M
ACCT_830N
ACCT_830O
ACCT_830P
ACCT_830Q
ACCT_830R
ACCT_830S
ACCT_830T
ACCT_566A
CertifiedBy
CertifiedBy_F
CertifiedBy_M
Acct_879A
Acct_879B
Acct_879C
Acct_879D
Acct_879E
Acct_879F
Acct_879G
Acct_879H
Acct_879I
Acct_879J
Acct_879K
Acct_879L
Acct_879M
Acct_879N
Acct_879O
Acct_879P
Acct_879Q
Acct_879R
Acct_879S
Acct_879T
Acct_888
Extension
Acct_834A1
Acct_834B1
Acct_834C1
Acct_834D1
Acct_834E1
Acct_834F1
Acct_834G1
Acct_834H1
Acct_834I1
Acct_834J1
Acct_834K1
Acct_834L1
Acct_834M1
Acct_834N1
Acct_834O1
Acct_834P1
Acct_834Q1
Acct_834R1
Acct_834S1
Acct_834T1
Acct_566B
Acct_887R
ACCT_879A1
ACCT_879A2
ACCT_879A3
ACCT_879A4
ACCT_879A5
ACCT_879B1
ACCT_879B2
ACCT_879B3
ACCT_879B4
ACCT_879B5
ACCT_879C1
ACCT_879C2
ACCT_879C3
ACCT_879C4
ACCT_879D1
ACCT_879D2
ACCT_879D3
ACCT_879D4
ACCT_879D5
ACCT_879D6
ACCT_879D7
ACCT_879D8
ACCT_879U
ACCT_879V
ACCT_879W
ACCT_879X
ACCT_879Y
ACCT_886H
ACCT_887S
ACCT_887T
ACCT_887U
ACCT_845A
ACCT_845B
ACCT_845C
ACCT_845D
ACCT_845E
ACCT_845F
ACCT_845G
ACCT_845H
ACCT_845I
ACCT_845J
ACCT_845K
ACCT_845L
ACCT_845M
ACCT_845N
ACCT_845O
ACCT_845P
ACCT_845Q
ACCT_845R
ACCT_845S
ACCT_845T
ACCT_879D9
Acct_855A
Acct_855B
Acct_855C
Acct_855D
Acct_855E
Acct_855F
Acct_855G
Acct_855H
Acct_855I
Acct_855J
Acct_855K
Acct_855L
Acct_855M
Acct_855N
Acct_855O
Acct_855P
Acct_855Q
Acct_855R
Acct_855S
Acct_855T
BondProvider
MemberMinorityStatus_y
EligibleMinorityStatus_y
MemberAsianAmerican
Acct_887V
Acct_879Q1
Acct_1027Z
Acct_1028Z
Acct_1029Z
ACCT_879B6
ACCT_879B7
ACCT_PI0007
ACCT_PI0008
ACCT_PI0009
ACCT_PP0026
ACCT_PP0028
ACCT_PP0030
ACCT_PP0032
ACCT_PP0033
Acct_879D10
ACCT_PC0013
ACCT_PI0011
ACCT_PI0012
ACCT_PI0013
ACCT_PI0014
ACCT_PI0015
ACCT_PI0016
ACCT_PI0017
ACCT_PI0018
ACCT_PP0034
ACCT_PP0035
ACCT_PP0036
ACCT_PP0058
ACCT_831A
ACCT_831B
ACCT_831C
ACCT_831D
ACCT_831E
ACCT_831F
ACCT_831G
ACCT_831H
ACCT_831I
ACCT_831J
ACCT_832A
ACCT_832B
ACCT_832C
ACCT_832D
ACCT_832E
ACCT_832F
ACCT_832G
ACCT_832H
ACCT_832I
ACCT_832J
ACCT_833A
ACCT_833B
ACCT_833C
ACCT_833D
ACCT_833E
ACCT_833F
ACCT_833G
ACCT_833H
ACCT_833I
ACCT_833J
ACCT_834A
ACCT_834B
ACCT_834C
ACCT_834D
ACCT_834E
ACCT_834F
ACCT_834G
ACCT_834H
ACCT_834I
ACCT_834J
ACCT_835A
ACCT_835B
ACCT_835C
ACCT_835D
ACCT_835E
ACCT_835F
ACCT_835G
ACCT_835H
ACCT_835I
ACCT_835J
ACCT_003
ACCT_064
ACCT_459
ACCT_617
ACCT_618
ACCT_786A
ACCT_786B
ACCT_878A
ACCT_878B
ACCT_878C
ACCT_878D
ACCT_878E
ACCT_878F
ACCT_878G
ACCT_878H
ACCT_878I
ACCT_878J
ACCT_878K
ACCT_878L
ACCT_878M
ACCT_878N
ACCT_831K
ACCT_831L
ACCT_831M
ACCT_831N
ACCT_831O
ACCT_831P
ACCT_831Q
ACCT_831R
ACCT_831S
ACCT_831T
ACCT_832K
ACCT_832L
ACCT_832M
ACCT_832N
ACCT_832O
ACCT_832P
ACCT_832Q
ACCT_832R
ACCT_832S
ACCT_832T
ACCT_833K
ACCT_833L
ACCT_833M
ACCT_833N
ACCT_833O
ACCT_833P
ACCT_833Q
ACCT_833R
ACCT_833S
ACCT_833T
ACCT_834K
ACCT_834L
ACCT_834M
ACCT_834N
ACCT_834O
ACCT_834P
ACCT_834Q
ACCT_834R
ACCT_834S
ACCT_834T
ACCT_835K
ACCT_835L
ACCT_835M
ACCT_835N
ACCT_835O
ACCT_835P
ACCT_835Q
ACCT_835R
ACCT_835S
ACCT_835T
ACCT_125F
ACCT_125G
ACCT_125H
ACCT_125I
ACCT_125J
ACCT_126F
ACCT_126G
ACCT_126H
ACCT_126I
ACCT_126J
ACCT_566
ACCT_619
ACCT_691A
ACCT_690
ACCT_690A
ACCT_691
ACCT_619A
ACCT_730B1
ACCT_730B2
ACCT_779
ACCT_836A
ACCT_836B
ACCT_836C
ACCT_836D
ACCT_836E
ACCT_836F
ACCT_836G
ACCT_836H
ACCT_836I
ACCT_836J
ACCT_836K
ACCT_836L
ACCT_836M
ACCT_836N
ACCT_836O
ACCT_836P
ACCT_836Q
ACCT_836R
ACCT_836S
ACCT_836T
ACCT_999A
ACCT_788
ACCT_878O
ACCT_837A
ACCT_837B
ACCT_837C
ACCT_837D
ACCT_837E
ACCT_837F
ACCT_837G
ACCT_837H
ACCT_837I
ACCT_837J
ACCT_837K
ACCT_837L
ACCT_837M
ACCT_837N
ACCT_837O
ACCT_837P
ACCT_837Q
ACCT_837R
ACCT_837S
ACCT_837T
ACCT_020G
ACCT_021G
ACCT_022G
ACCT_023G
ACCT_041G
ACCT_020H
ACCT_021H
ACCT_022H
ACCT_023H
ACCT_041H
ACCT_550C
ACCT_551C
ACCT_550D
ACCT_551D
ACCT_550E
ACCT_551E
ACCT_550F
ACCT_551F
ACCT_550G
ACCT_551G
ACCT_550H
ACCT_551H
ACCT_818A
ACCT_631
ACCT_632
ACCT_633
ACCT_634
ACCT_635
ACCT_636
ACCT_637
ACCT_638
ACCT_639
ACCT_641
ACCT_1000A
ACCT_1000B
ACCT_1000C
ACCT_1001A
ACCT_1001B
ACCT_1001C
ACCT_1002A
ACCT_1002B
ACCT_1002C
ACCT_036A
ACCT_036B
ACCT_036C
ACCT_036D
ACCT_036E
ACCT_037A
ACCT_037B
ACCT_037C
ACCT_037D
ACCT_037E
ACCT_038A
ACCT_038B
ACCT_038C
ACCT_038D
ACCT_038E
ACCT_039A
ACCT_039B
ACCT_039C
ACCT_039D
ACCT_039E
ACCT_642

In [34]:
variables = ['Acct_010', 'Acct_025B', 'Acct_083', 'Acct_998', 'Acct_564A', 'Acct_799I', 
           'Acct_566', 'Acct_025A', 'Acct_031A', 'Acct_031B', 'Acct_083', 'Acct_084',
            'Acct_100','Acct_115', 'Acct_120', 'Acct_124', 'Acct_131', 'Acct_457',
            'Acct_564A', 'Acct_564B', 'Acct_566', 'Acct_997', 'Acct_998']

In [35]:
#variables = [col.upper() for col in columns]

In [36]:
# add minority variables to the variable list 
variables += [
    'EligibleMinorityStatus', 'EligibleAfricanAmerican', 'EligibleAsianAmerican', 'EligibleHispanicAmerican', 'EligibleNativeAmerican',
    'MemberAfricanAmerican', 'MemberAsianAmerican', 'MemberHispanicAmerican', 'MemberMinorityStatus', 'MemberNativeAmerican',
    'FOMAsianAmerican', 'FOMBlackAmerican', 'FOMHispanicAmerican', 'FOMMinorityStatus', 'FOMNativeAmerican',
    'MemberAfricanAmerican', 'MemberAsianAmerican', 'MemberHispanicAmerican', 'MemberMinorityStatus', 'MemberNativeAmerican',
    'CurMemAsianAmerican', 'CurMemBlackAmerican', 'CurMemHispanicAmerican', 'CurMemMinorityStatus', 'CurMemNativeAmerican'
]

In [37]:
names

,Account,AcctName,AcctDesc,TableName,Annualize,CBSAccount,FPRAccount,STATAcctMain,STATAcctState,STATAcctGraph,STATAcctTable8,STATUS
0,Acct_001,Amount - Total Other Loans (Purchased or to no...,Include the dollar amount of outstanding loans...,FS220A,False,True,True,True,True,False,False,False
1,Acct_002,Amount of Leases Receivable,"Leases Receivable. Include the rate, number, a...",FS220A,False,False,False,False,False,False,False,True
2,Acct_003,Loans Held for Sale,Loans Held for Sale. Report the amount of outs...,FS220C,False,False,False,False,False,False,False,True
3,Acct_007,Land and Building,"Land and building, less depreciation on buildi...",FS220,False,True,True,True,True,False,True,True
4,Acct_008,Other Fixed Assets,All other fixed assets such as furniture and f...,FS220,False,True,True,True,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
3371,President_F,President of the Board First Name,First Name of board chairperson.,FS220D,False,False,False,False,False,False,False,True
3372,President_M,President of the Board Middle Initial,Middle Initial of board chairperson.,FS220D,False,False,False,False,False,False,False,True
3373,Principal,Principal Last Name,The last name person responsible for the day t...,FS220D,False,False,False,False,False,False,False,False
3374,Principal_F,Principal First Name,The first name person responsible for the day ...,FS220D,False,False,False,False,False,False,False,False
3375,Principal_M,Principal Middle Name,The middle inital of the person responsible fo...,FS220D,False,False,False,False,False,False,False,False

In [38]:
# Filter rows in the 'names' DataFrame where the 'Account' column matches any value in 'variables'
filtered_names = names[names["Account"].isin(variables)]

filtered_names.to_csv('/Users/artyom/Documents/work/CreditUnions/filtered_names.csv', index=False)

# Geocoding Locations

In [39]:
import geopandas as gpd

In [40]:
locations_f.columns

Index(['CU_NUMBER', 'CYCLE_DATE', 'JOIN_NUMBER', 'SiteId', 'CU_NAME',
       'SiteName', 'SiteTypeName', 'MainOffice', 'PhysicalAddressLine1',
       'PhysicalAddressLine2', 'PhysicalAddressCity',
       'PhysicalAddressStateCode', 'PhysicalAddressPostalCode',
       'PhysicalAddressCountyName', 'PhysicalAddressCountry',
       'MailingAddressLine1', 'MailingAddressLine2', 'MailingAddressCity',
       'MailingAddressStateCode', 'MailingAddressStateName',
       'MailingAddressPostalCode', 'PhoneNumber', 'HoursOfOperation',
       'MemberServices', 'ATM', 'DriveThru', 'Shrd_Serv_Cntr_Net',
       'SiteFunctionName', 'PhysicalAddressStateName', 'YEAR_OPENED',
       'TOM_CODE', 'IsMDI'],
      dtype='object')

In [41]:
import pandas as pd

def combine_address(row):
    parts = [
        row['PhysicalAddressLine1'],
        row['PhysicalAddressLine2'] if pd.notnull(row['PhysicalAddressLine2']) and row['PhysicalAddressLine2'].strip() != '' else '',
        row['PhysicalAddressCity'],
        row['PhysicalAddressStateCode'],
        str(row['PhysicalAddressPostalCode']),
        row['PhysicalAddressCountry']
    ]
    return ', '.join([str(part).strip() for part in parts if part and str(part).strip() != ''])

# Create new column
locations_f['FullPhysicalAddress'] = locations_f.apply(combine_address, axis=1)

In [42]:
locations_f

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,SiteId,CU_NAME,SiteName,SiteTypeName,MainOffice,PhysicalAddressLine1,PhysicalAddressLine2,...,MemberServices,ATM,DriveThru,Shrd_Serv_Cntr_Net,SiteFunctionName,PhysicalAddressStateName,YEAR_OPENED,TOM_CODE,IsMDI,FullPhysicalAddress
0,1,12/31/2024 0:00:00,2,45553,MORRIS SHEPPARD TEXARKANA,MORRIS SHEPPARD TEXARKANA FCU,Corporate Office,Yes,419 W 4TH ST,NaN,...,1.0,0.0,0.0,0.0,NaN,NaN,1934,36,False,"419 W 4TH ST, TEXARKANA, TX, 75501, United States"
1,6,12/31/2024 0:00:00,7,40302,THE NEW ORLEANS FIREMEN'S,Slidell,Branch Office,No,1512 Gause Blvd,NaN,...,1.0,1.0,1.0,0.0,NaN,NaN,1934,36,False,"1512 Gause Blvd, Slidell, LA, 70458, United St..."
2,6,12/31/2024 0:00:00,7,41260,THE NEW ORLEANS FIREMEN'S,Metairie,Corporate Office,Yes,4401 W Napoleon Ave,NaN,...,1.0,0.0,0.0,0.0,NaN,NaN,1934,36,False,"4401 W Napoleon Ave, Metairie, LA, 70001-2406,..."
3,6,12/31/2024 0:00:00,7,41353,THE NEW ORLEANS FIREMEN'S,Westbank,Branch Office,No,5163 General DeGaulle Dr Ste F,Suite F,...,1.0,0.0,0.0,0.0,NaN,NaN,1934,36,False,"5163 General DeGaulle Dr Ste F, Suite F, New O..."
4,6,12/31/2024 0:00:00,7,41368,THE NEW ORLEANS FIREMEN'S,Mandeville,Branch Office,No,238 Lafitte St,NaN,...,1.0,1.0,0.0,0.0,NaN,NaN,1934,36,False,"238 Lafitte St, Mandeville, LA, 70448, United ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22982,97113,12/31/2024 0:00:00,8532,51850,"KH CREDIT UNION, INC.",Fort Hamilton Hospital,Other,NaN,630 Eaton Ave,NaN,...,NaN,NaN,NaN,NaN,ATM,Ohio,1964,99,False,"630 Eaton Ave, Hamilton, OH, 45013, United States"
22983,97113,12/31/2024 0:00:00,8532,51851,"KH CREDIT UNION, INC.",Beavercreek Soin ATM,Other,NaN,3535 Pentagon Blvd,NaN,...,NaN,NaN,NaN,NaN,ATM,Ohio,1964,99,False,"3535 Pentagon Blvd, Beavercreek, OH, 45431-170..."
22984,97113,12/31/2024 0:00:00,8532,51852,"KH CREDIT UNION, INC.",Prestige Plaza ATM,Other,NaN,1 Prestige Plaza Dr,NaN,...,NaN,NaN,NaN,NaN,ATM,Ohio,1964,99,False,"1 Prestige Plaza Dr, Miamisburg, OH, 45342, Un..."
22985,97113,12/31/2024 0:00:00,8532,51853,"KH CREDIT UNION, INC.",Cancer Center ATM,Other,NaN,3700 Southern Blvd,NaN,...,NaN,NaN,NaN,NaN,ATM,Ohio,1964,99,False,"3700 Southern Blvd, Kettering, OH, 45429, Unit..."
22986,97113,12/31/2024 0:00:00,8532,51854,"KH CREDIT UNION, INC.",Troy ATM,Other,NaN,600 W Main St,NaN,...,NaN,NaN,NaN,NaN,ATM,Ohio,1964,99,False,"600 W Main St, Troy, OH, 45373, United States"

In [43]:
# Export locations for geocoding in a separate notebook
locations_f.to_csv('locations_geocoded_full_fixed.csv', index=False)

In [44]:
# Import geocoded locations without first column
locations_g = pd.read_csv('/Users/artyom/Documents/work/CreditUnions/locations_geocoded.csv', encoding='utf-8')
locations_g.drop(columns=['Unnamed: 0'], inplace=True)
locations_g

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,SiteId,CU_NAME,SiteName,SiteTypeName,MainOffice,PhysicalAddressLine1,PhysicalAddressLine2,...,DriveThru,Shrd_Serv_Cntr_Net,SiteFunctionName,PhysicalAddressStateName,YEAR_OPENED,TOM_CODE,IsMDI,FullPhysicalAddress,latitudes,longitudes
0,1,12/31/2024 0:00:00,2,45553,MORRIS SHEPPARD TEXARKANA,MORRIS SHEPPARD TEXARKANA FCU,Corporate Office,Yes,419 W 4TH ST,NaN,...,0.0,0.0,NaN,NaN,1934,36,False,"419 W 4TH ST, TEXARKANA, TX, 75501, United States",29.993905,-90.179249
1,6,12/31/2024 0:00:00,7,40302,THE NEW ORLEANS FIREMEN'S,Slidell,Branch Office,No,1512 Gause Blvd,NaN,...,1.0,0.0,NaN,NaN,1934,36,False,"1512 Gause Blvd, Slidell, LA, 70458, United St...",30.284789,-89.757589
2,6,12/31/2024 0:00:00,7,41260,THE NEW ORLEANS FIREMEN'S,Metairie,Corporate Office,Yes,4401 W Napoleon Ave,NaN,...,0.0,0.0,NaN,NaN,1934,36,False,"4401 W Napoleon Ave, Metairie, LA, 70001-2406,...",33.421956,-94.047144
3,6,12/31/2024 0:00:00,7,41353,THE NEW ORLEANS FIREMEN'S,Westbank,Branch Office,No,5163 General DeGaulle Dr Ste F,Suite F,...,0.0,0.0,NaN,NaN,1934,36,False,"5163 General DeGaulle Dr Ste F, Suite F, New O...",29.911799,-90.000273
4,6,12/31/2024 0:00:00,7,41368,THE NEW ORLEANS FIREMEN'S,Mandeville,Branch Office,No,238 Lafitte St,NaN,...,0.0,0.0,NaN,NaN,1934,36,False,"238 Lafitte St, Mandeville, LA, 70448, United ...",30.356082,-90.068717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22982,97113,12/31/2024 0:00:00,8532,51850,"KH CREDIT UNION, INC.",Fort Hamilton Hospital,Other,NaN,630 Eaton Ave,NaN,...,NaN,NaN,ATM,Ohio,1964,99,False,"630 Eaton Ave, Hamilton, OH, 45013, United States",39.633172,-84.204231
22983,97113,12/31/2024 0:00:00,8532,51851,"KH CREDIT UNION, INC.",Beavercreek Soin ATM,Other,NaN,3535 Pentagon Blvd,NaN,...,NaN,NaN,ATM,Ohio,1964,99,False,"3535 Pentagon Blvd, Beavercreek, OH, 45431-170...",39.771893,-84.062738
22984,97113,12/31/2024 0:00:00,8532,51852,"KH CREDIT UNION, INC.",Prestige Plaza ATM,Other,NaN,1 Prestige Plaza Dr,NaN,...,NaN,NaN,ATM,Ohio,1964,99,False,"1 Prestige Plaza Dr, Miamisburg, OH, 45342, Un...",39.696102,-84.190744
22985,97113,12/31/2024 0:00:00,8532,51853,"KH CREDIT UNION, INC.",Cancer Center ATM,Other,NaN,3700 Southern Blvd,NaN,...,NaN,NaN,ATM,Ohio,1964,99,False,"3700 Southern Blvd, Kettering, OH, 45429, Unit...",39.638103,-84.228142
22986,97113,12/31/2024 0:00:00,8532,51854,"KH CREDIT UNION, INC.",Troy ATM,Other,NaN,600 W Main St,NaN,...,NaN,NaN,ATM,Ohio,1964,99,False,"600 W Main St, Troy, OH, 45373, United States",40.042054,-84.208845

In [45]:
locations_g[locations_g["CU_NAME"] == 'SERVICE']

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,SiteId,CU_NAME,SiteName,SiteTypeName,MainOffice,PhysicalAddressLine1,PhysicalAddressLine2,...,DriveThru,Shrd_Serv_Cntr_Net,SiteFunctionName,PhysicalAddressStateName,YEAR_OPENED,TOM_CODE,IsMDI,FullPhysicalAddress,latitudes,longitudes
11372,24921,12/31/2024 0:00:00,5682,24779,SERVICE,Bedford Branch Office,Branch Office,No,14 Colby Ct,NaN,...,1.0,1.0,NaN,NaN,1957,35,False,"14 Colby Ct, Bedford, NH, 03110, United States",42.963317,-71.482610
11373,24921,12/31/2024 0:00:00,5682,24786,SERVICE,Falmouth Branch Office,Branch Office,No,199 Worcester Ct,NaN,...,1.0,1.0,NaN,NaN,1957,35,False,"199 Worcester Ct, Falmouth, MA, 02540, United ...",41.558466,-70.597410
11374,24921,12/31/2024 0:00:00,5682,24794,SERVICE,Keene Branch Office,Branch Office,No,403 Winchester St,NaN,...,1.0,1.0,NaN,NaN,1957,35,False,"403 Winchester St, Keene, NH, 03431, United St...",42.920982,-72.291738
11375,24921,12/31/2024 0:00:00,5682,24797,SERVICE,Dartmouth Hitchcock Medical Center Branch,Branch Office,No,1 Medical Center Dr,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"1 Medical Center Dr, Lebanon, NH, 03756, Unite...",43.084695,-70.810431
11376,24921,12/31/2024 0:00:00,5682,24805,SERVICE,Pease Branch Office,Branch Office,No,14 Manchester Sq Ste 190,NaN,...,1.0,1.0,NaN,NaN,1957,35,False,"14 Manchester Sq Ste 190, Portsmouth, NH, 0380...",43.037871,-70.777069
11377,24921,12/31/2024 0:00:00,5682,24811,SERVICE,Portsmouth Branch,Branch Office,No,2032 Lafayette Rd,NaN,...,1.0,1.0,NaN,NaN,1957,35,False,"2032 Lafayette Rd, Portsmouth, NH, 03801, Unit...",43.678113,-72.273635
11378,24921,12/31/2024 0:00:00,5682,24813,SERVICE,Salem Branch Office,Branch Office,No,159 N Broadway,NaN,...,1.0,1.0,NaN,NaN,1957,35,False,"159 N Broadway, Salem, NH, 03079, United States",42.787249,-71.233144
11379,24921,12/31/2024 0:00:00,5682,24826,SERVICE,Tycom Branch,Branch Office,No,100 Piscataqua Dr,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"100 Piscataqua Dr, Newington, NH, 03801, Unite...",43.099942,-70.796484
11380,24921,12/31/2024 0:00:00,5682,24833,SERVICE,Rochester Branch Office,Branch Office,No,90 S Main St,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"90 S Main St, Rochester, NH, 03867, United States",43.237317,-70.881832
11381,24921,12/31/2024 0:00:00,5682,24836,SERVICE,Somersworth Branch Office,Branch Office,No,15 Penny Ln,NaN,...,1.0,1.0,NaN,NaN,1957,35,False,"15 Penny Ln, Somersworth, NH, 03878, United St...",43.102633,-70.809356
11382,24921,12/31/2024 0:00:00,5682,24840,SERVICE,Manchester In-Store Branch,Branch Office,No,300 Keller St,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"300 Keller St, Manchester, NH, 03103, United S...",42.951604,-71.438991
11383,24921,12/31/2024 0:00:00,5682,24842,SERVICE,Newington In-Store Branch,Branch Office,No,2200 Woodbury Ave,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"2200 Woodbury Ave, Newington, NH, 03801, Unite...",43.301436,-70.973028
11384,24921,12/31/2024 0:00:00,5682,24844,SERVICE,Portsmouth In-Store Branch,Branch Office,No,2460 Lafayette Rd,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"2460 Lafayette Rd, Portsmouth, NH, 03801, Unit...",43.034646,-70.789237
11385,24921,12/31/2024 0:00:00,5682,24845,SERVICE,Salem In-Store Branch,Branch Office,No,300 N Broadway # 344,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"300 N Broadway # 344, Salem, NH, 03079, United...",42.798815,-71.239279
11386,24921,12/31/2024 0:00:00,5682,24851,SERVICE,Rochester In-Store,Branch Office,No,116 Farmington Rd,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"116 Farmington Rd, Rochester, NH, 03867, Unite...",43.336404,-71.011656
11387,24921,12/31/2024 0:00:00,5682,24854,SERVICE,Epping In-Store Branch,Branch Office,No,35 Fresh River Rd,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"35 Fresh River Rd, Epping, NH, 03042, United S...",43.028362,-71.070114
11388,24921,12/31/2024 0:00:00,5682,25845,SERVICE,Ansbach Branch Office,Branch Office,No,Unit 28733,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"Unit 28733, APO, nan, 09177, Germany",51.110631,10.392278
11389,24921,12/31/2024 0:00:00,5682,25847,SERVICE,Contact Center,Corporate Office,No,3003 Lafayette Rd,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"3003 Lafayette Rd, Portsmouth, NH, 03801, Unit...",43.025505,-70.793414
11390,24921,12/31/2024 0:00:00,5682,25853,SERVICE,Baumholder Branch Office,Branch Office,No,Unit 23817,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"Unit 23817, APO, nan, 09034, Germany",50.872400,12.915379
11391,24921,12/31/2024 0:00:00,5682,25854,SERVICE,Garmisch Branch Office,Branch Office,No,Unit 24527,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"Unit 24527, APO, nan, 09053, Germany",51.110631,10.392278
11392,24921,12/31/2024 0:00:00,5682,25858,SERVICE,Grafenwoehr Branch Office,Branch Office,No,Unit 28130,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"Unit 28130, APO, nan, 09114, Germany",50.872400,12.915379
11393,24921,12/31/2024 0:00:00,5682,25869,SERVICE,Hohenfels Branch Office,Branch Office,No,Unit 28216,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"Unit 28216, APO, nan, 09173, Germany",49.429170,7.696900
11394,24921,12/31/2024 0:00:00,5682,25871,SERVICE,Kapaun/Vogelweh Branch Office,Branch Office,No,Kpaun Air Station Building 2762,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"Kpaun Air Station Building 2762, Kaiserslauter...",49.429170,7.696900
11395,24921,12/31/2024 0:00:00,5682,25873,SERVICE,Contact Center Overseas,Other,NaN,Unit 8195,NaN,...,NaN,NaN,ATM,NaN,1957,35,False,"Unit 8195, APO, nan, 09021, Germany",50.826186,12.936437
11396,24921,12/31/2024 0:00:00,5682,25882,SERVICE,Ramstein Branch Office,Branch Office,No,Unit 3450,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"Unit 3450, APO, nan, 09094, Germany",50.825617,12.904292
11397,24921,12/31/2024 0:00:00,5682,25887,SERVICE,Spangdahlem Branch Office,Branch Office,No,Unite 3770,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"Unite 3770, APO, nan, 09126, Germany",50.826186,12.936437
11398,24921,12/31/2024 0:00:00,5682,25890,SERVICE,Stuttgart-Patch Branch Office,Branch Office,No,Unit 30401,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"Unit 30401, APO, nan, 09107, Germany",51.110631,10.392278
11399,24921,12/31/2024 0:00:00,5682,25893,SERVICE,Vilseck Branch Office,Branch Office,No,Unit 28038,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"Unit 28038, APO, nan, 09112, Germany",50.825617,12.904292
11400,24921,12/31/2024 0:00:00,5682,25901,SERVICE,Stuttgart-Panzer Branch Office,Branch Office,No,Unit 30401,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"Unit 30401, APO, nan, 09107, Germany",51.110631,10.392278
11401,24921,12/31/2024 0:00:00,5682,44199,SERVICE,Ramstein- KMCC,Branch Office,No,"Unite 3450, KMCC Bldg 3336 Suite M20",NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"Unite 3450, KMCC Bldg 3336 Suite M20, APO, nan...",42.726830,-71.424279
11402,24921,12/31/2024 0:00:00,5682,50386,SERVICE,Hudson Branch,Branch Office,No,254 Lowell Rd,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"254 Lowell Rd, Hudson, NH, 03051, United States",42.989188,-70.967566
11403,24921,12/31/2024 0:00:00,5682,52995,SERVICE,Hampton Branch,Branch Office,No,887 Lafayette Rd,NaN,...,1.0,1.0,NaN,NaN,1957,35,False,"887 Lafayette Rd, Hampton, NH, 03842, United S...",42.955585,-70.833331
11404,24921,12/31/2024 0:00:00,5682,52996,SERVICE,Exeter Branch,Branch Office,No,109 Epping Rd,NaN,...,1.0,1.0,NaN,NaN,1957,35,False,"109 Epping Rd, Exeter, NH, 03833, United States",42.901767,-71.326702
11405,24921,12/31/2024 0:00:00,5682,52997,SERVICE,Concord In-Store,Branch Office,No,344 Loudon Rd,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"344 Loudon Rd, Concord, NH, 03301, United States",43.025505,-70.793414
11406,24921,12/31/2024 0:00:00,5682,52998,SERVICE,Derry In-Store,Branch Office,No,11 Ashleigh Dr,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"11 Ashleigh Dr, Derry, NH, 03038, United States",43.229482,-71.481275
11407,24921,12/31/2024 0:00:00,5682,52999,SERVICE,Corporate Headquarters,Corporate Office,Yes,3003 Lafayette Rd,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"3003 Lafayette Rd, Portsmouth, NH, 03801, Unit...",49.525795,7.849837
11408,24921,12/31/2024 0:00:00,5682,53000,SERVICE,Hinsdale In-Store Branch,Branch Office,No,724 Brattleboro Rd,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"724 Brattleboro Rd, Hinsdale, NH, 03451, Unite...",42.811197,-72.533103
11409,24921,12/31/2024 0:00:00,5682,53001,SERVICE,Plymouth In-Store Branch,Branch Office,No,683 Tenney Mountain Hwy,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"683 Tenney Mountain Hwy, Plymouth, NH, 03264, ...",43.528905,-71.471779
11410,24921,12/31/2024 0:00:00,5682,53002,SERVICE,Sembach Branch Office,Branch Office,No,Unit 27205,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"Unit 27205, APO, nan, 67681, Germany",42.811197,-72.533103
11411,24921,12/31/2024 0:00:00,5682,53003,SERVICE,Laconia branch,Branch Office,No,11 Veterans Sq,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"11 Veterans Sq, Laconia, NH, 03246, United States",43.771039,-71.742339
11412,24921,12/31/2024 0:00:00,5682,53004,SERVICE,Franklin Branch Office,Branch Office,No,886 Central St,NaN,...,1.0,1.0,NaN,NaN,1957,35,False,"886 Central St, Franklin, NH, 03235, United St...",42.782398,-71.502861
11413,24921,12/31/2024 0:00:00,5682,53005,SERVICE,Nashua Branch Office,Branch Office,No,337 Amherst St,NaN,...,1.0,1.0,NaN,NaN,1957,35,False,"337 Amherst St, Nashua, NH, 03063, United States",43.638025,-72.272357
11414,24921,12/31/2024 0:00:00,5682,53006,SERVICE,Lebanon Branch,Branch Office,No,225 Mechanic St,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"225 Mechanic St, Lebanon, NH, 03766-1510, Unit...",43.446839,-71.625959
11415,24921,12/31/2024 0:00:00,5682,53007,SERVICE,Seabrook In-Store Branch,Branch Office,No,700 Lafayette Rd,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"700 Lafayette Rd, Seabrook, NH, 03874, United ...",42.895714,-70.870710
11416,24921,12/31/2024 0:00:00,5682,53008,SERVICE,Berlin Branch Office,Branch Office,No,200 Coos St,NaN,...,1.0,0.0,NaN,NaN,1957,35,False,"200 Coos St, Berlin, NH, 03570, United States",44.468908,-71.171374
11417,24921,12/31/2024 0:00:00,5682,53009,SERVICE,Lancaster Branch Office,Branch Office,No,148 Main St,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"148 Main St, Lancaster, NH, 03584-3059, United...",44.492288,-71.570785
11418,24921,12/31/2024 0:00:00,5682,53010,SERVICE,Amherest In-Store Branch,Branch Office,No,85 State ROUTE 101A,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"85 State ROUTE 101A, Amherst, NH, 03031-2216, ...",42.811185,-71.579056
11419,24921,12/31/2024 0:00:00,5682,53011,SERVICE,Kleber Branch Office,Branch Office,No,Unit 23152,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"Unit 23152, APO, nan, 09054, Germany",44.426341,-71.192972
11420,24921,12/31/2024 0:00:00,5682,53012,SERVICE,Gorham In-store Branch,Branch Office,No,561 Main St,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"561 Main St, Gorham, NH, 03581-4901, United St...",42.811185,-71.579056
11421,24921,12/31/2024 0:00:00,5682,53013,SERVICE,Grand Forks AFB Branch,Branch Office,No,589 Holzapple St Bldg 210,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"589 Holzapple St Bldg 210, Grand Forks Afb, ND...",47.950918,-97.375822
11422,24921,12/31/2024 0:00:00,5682,53014,SERVICE,Pease Air National Guard Base,Branch Office,No,153 Newmarket St,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"153 Newmarket St, NEWINGTON, NH, 03801-7867, U...",43.234739,-70.880656
11423,24921,12/31/2024 0:00:00,5682,53015,SERVICE,Somersworth In-Store Branch,Branch Office,No,59 Waltons Way,NaN,...,0.0,0.0,NaN,NaN,1957,35,False,"59 Waltons Way, Somersworth, NH, 03878, United...",43.089380,-70.815381
11424,24921,12/31/2024 0:00:00,5682,53017,SERVICE,UNH Branch,Branch Office,No,155 Main St,NaN,...,0.0,1.0,NaN,NaN,1957,35,False,"155 Main St, Durham, NH, 03824, United States",43.140000,-70.939468
11425,24921,12/31/2024 0:00:00,5682,53019,SERVICE,Rocester Drive Thru,Branch Office,No,48 Portland St,NaN,...,1.0,0.0,NaN,NaN,1957,35,False,"48 Portland St, Rochester, NH, 03867-2711, Uni...",43.030382,-71.070965
11426,24921,12/31/2024 0:00:00,5682,53021,SERVICE,Concord,Branch Office,No,8 Merchants Way,NaN,...,1.0,1.0,NaN,NaN,1957,35,False,"8 Merchants Way, Concord, NH, 03301, United St...",43.302696,-70.975517
11427,24921,12/31/2024 0:00:00,5682,53022,SERVICE,Epping Branch,Branch Office,No,5 Fresh River Rd,NaN,...,1.0,1.0,NaN,NaN,1957,35,False,"5 Fresh River Rd, Epping, NH, 03042-2222, Unit...",43.288401,-71.579257
17192,66530,12/31/2024 0:00:00,20752,16529,SERVICE,Main Office,Corporate Office,Yes,2850 S Ashland Ave,NaN,...,0.0,0.0,NaN,NaN,1934,99,False,"2850 S Ashland Ave, Green Bay, WI, 54304-5304,...",44.245853,-91.473831

# Merging Location Data with Financial Data

This section is dedicated to creating proper names for the financial data that we merged in the previous section. One of the main challengers here, that the variables names are mapped using difference syntax.

In [46]:
merged_fs220

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,UPDATE_DATE,ACCT_007,ACCT_008,ACCT_009,ACCT_010,ACCT_011C,ACCT_013,...,ACCT_038B,ACCT_038C,ACCT_038D,ACCT_038E,ACCT_039A,ACCT_039B,ACCT_039C,ACCT_039D,ACCT_039E,ACCT_642
0,1,12/31/2024 0:00:00,2,1/29/2025 10:45:12 PM,41785,5201,0,11835153,0,10456209,...,0,0,0,0,0,0,0,0,0,0
1,6,12/31/2024 0:00:00,7,1/30/2025 10:36:36 PM,2868178,750856,0,269952063,0,204597639,...,0,0,0,0,0,0,0,0,0,0
2,12,12/31/2024 0:00:00,11,1/23/2025 10:14:11 PM,4871838,488776,0,60540924,0,55308291,...,0,0,0,0,0,0,0,0,0,0
3,13,12/31/2024 0:00:00,12,1/29/2025 10:16:22 PM,18140884,2568776,0,1166537765,0,930699777,...,0,0,0,0,0,0,0,0,0,0
4,16,12/31/2024 0:00:00,14,1/16/2025 10:09:26 PM,0,2147,0,9364728,0,8039127,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4545,24958,12/31/2024 0:00:00,26474,1/27/2025 10:26:42 PM,0,13253,0,2574318,0,1196783,...,0,0,0,0,0,0,0,0,0,0
4546,68740,12/31/2024 0:00:00,26475,1/31/2025 10:01:16 PM,0,2877,0,1092983,0,76,...,0,0,0,0,0,0,0,0,0,0
4547,24960,12/31/2024 0:00:00,26476,1/22/2025 10:06:09 PM,0,0,0,289005,0,0,...,0,0,0,0,0,0,0,0,0,0
4548,24961,12/31/2024 0:00:00,26477,2/6/2025 10:03:02 PM,0,0,0,1990,0,0,...,0,0,0,0,0,0,0,0,0,0
4549,24968,12/31/2024 0:00:00,26478,2/5/2025 10:00:57 PM,0,0,0,350000,0,0,...,0,0,0,0,0,0,0,0,0,0

In [47]:
for i in merged_fs220.columns:
    print(i)

CU_NUMBER
CYCLE_DATE
JOIN_NUMBER
UPDATE_DATE
ACCT_007
ACCT_008
ACCT_009
ACCT_010
ACCT_011C
ACCT_013
ACCT_018
ACCT_019
ACCT_021B
ACCT_022B
ACCT_023B
ACCT_025A
ACCT_025B
ACCT_031A
ACCT_031B
ACCT_041B
ACCT_042
ACCT_058C
ACCT_065
ACCT_067
ACCT_068
ACCT_069
ACCT_080
ACCT_083
ACCT_084
ACCT_100
ACCT_300
ACCT_340
ACCT_380
ACCT_386
ACCT_387
ACCT_388
ACCT_392
ACCT_400
ACCT_457
ACCT_521
ACCT_522
ACCT_523
ACCT_524
ACCT_550
ACCT_551
ACCT_552
ACCT_562
ACCT_563
ACCT_602
ACCT_630
ACCT_652A
ACCT_652B1
ACCT_652B2
ACCT_655A
ACCT_655B1
ACCT_655B2
ACCT_656C
ACCT_657
ACCT_658
ACCT_662
ACCT_668
ACCT_671
ACCT_672A
ACCT_672B1
ACCT_672B2
ACCT_703
ACCT_704
ACCT_705
ACCT_706
ACCT_707
ACCT_708
ACCT_710
ACCT_712
ACCT_713
ACCT_714
ACCT_715
ACCT_716
ACCT_718
ACCT_719
ACCT_720
ACCT_721
ACCT_722
ACCT_723
ACCT_724
ACCT_730
ACCT_741A
ACCT_741B1
ACCT_741B2
ACCT_742A
ACCT_742B1
ACCT_742B2
ACCT_746A
ACCT_746B1
ACCT_746B2
ACCT_749
ACCT_750A
ACCT_750B1
ACCT_750B2
ACCT_751
ACCT_755
ACCT_760C
ACCT_761C
ACCT_771
ACCT_775
ACCT_794
ACCT_798
ACCT_799A
ACCT_799B1
ACCT_799B2
ACCT_825
ACCT_860C
ACCT_880
ACCT_902
ACCT_906A
ACCT_908A
ACCT_908C
ACCT_911
ACCT_931
ACCT_940
ACCT_959
ACCT_960
ACCT_968
ACCT_973
ACCT_975
ACCT_976
ACCT_991
Acct_965A
Acct_965B
Acct_965C
Acct_965D
ACCT_020A
ACCT_020B
ACCT_024A
ACCT_024B
ACCT_042A
ACCT_090A
ACCT_090B
ACCT_090C
ACCT_090D
ACCT_099A
ACCT_143A
ACCT_143B
ACCT_143C
ACCT_143D
ACCT_400A
ACCT_400B
ACCT_400C
ACCT_400D
ACCT_400F
ACCT_459A
ACCT_463A
ACCT_475A
ACCT_475B
ACCT_475C
ACCT_475D
ACCT_691B
ACCT_691C
ACCT_692
ACCT_692A
ACCT_704A
ACCT_704B
ACCT_704C
ACCT_704D
ACCT_704E
ACCT_705A
ACCT_705B
ACCT_708B
ACCT_720A
ACCT_720B
ACCT_720C
ACCT_720D
ACCT_720E
ACCT_721A
ACCT_721B
ACCT_724B
ACCT_733A
ACCT_745C1
ACCT_745C2
ACCT_796C1
ACCT_796C2
ACCT_797C1
ACCT_797C2
ACCT_799C1
ACCT_799C2
ACCT_965C1
ACCT_965C2
ACCT_088
ACCT_799A1
ACCT_672B
ACCT_672C1
ACCT_672C2
ACCT_672D
ACCT_744B
ACCT_744C1
ACCT_744C2
ACCT_744D
ACCT_652B
ACCT_652C1
ACCT_652C2
ACCT_652D
ACCT_766A
ACCT_766B
ACCT_766C1
ACCT_766C2
ACCT_766D
ACCT_766E
ACCT_798A1
ACCT_798A2
ACCT_798A3
ACCT_009A
ACCT_009B
ACCT_009C
ACCT_769A1
ACCT_769B1
ACCT_616
ACCT_616A
ACCT_704A1
ACCT_704C1
ACCT_980
ACCT_742C1
ACCT_742C2
ACCT_020J
ACCT_020K
ACCT_020L
ACCT_021J
ACCT_021K
ACCT_021L
ACCT_022J
ACCT_022K
ACCT_022L
ACCT_023J
ACCT_023K
ACCT_023L
ACCT_041J
ACCT_041K
ACCT_041L
Acct_1019
Acct_1019A
Acct_1019B
Acct_1019C
Acct_1019D
Acct_1019E
Acct_789A
Acct_789A1
Acct_789B
Acct_789B1
ACCT_PG0001
ACCT_PP0037
ACCT_PP0038
ACCT_PP0039
ACCT_PP0040
ACCT_PP0041
ACCT_PP0042
ACCT_PP0043
ACCT_PP0044
ACCT_PP0045
ACCT_PP0046
ACCT_PP0047
ACCT_PP0048
ACCT_PR0001
ACCT_PR0002
ACCT_PR0003
ACCT_PR0004
BoardAsianAmerican
BoardBlackAmerican
BoardHispanicAmerican
BoardMinorityStatus
BoardNativeAmerican
CurMemAsianAmerican
CurMemBlackAmerican
CurMemHispanicAmerican
CurMemMinorityStatus
CurMemNativeAmerican
EligibleMinorityStatus_x
FOMAsianAmerican
FOMBlackAmerican
FOMHispanicAmerican
FOMMinorityStatus
FOMNativeAmerican
MemberMinorityStatus_x
ACCT_001
ACCT_011A
ACCT_011B1
ACCT_011B2
ACCT_013A
ACCT_013B1
ACCT_013B2
ACCT_014
ACCT_017
ACCT_018A
ACCT_018B1
ACCT_018B2
ACCT_021A
ACCT_022A
ACCT_023A
ACCT_041A
ACCT_058A
ACCT_058B1
ACCT_058B2
ACCT_062
ACCT_063
ACCT_076
ACCT_077
ACCT_078
ACCT_079
ACCT_081
ACCT_082
ACCT_090
ACCT_099
ACCT_110
ACCT_119
ACCT_120
ACCT_124
ACCT_125A
ACCT_125B
ACCT_125C
ACCT_125D
ACCT_125E
ACCT_126A
ACCT_126B
ACCT_126C
ACCT_126D
ACCT_126E
ACCT_131
ACCT_132
ACCT_133
ACCT_134
ACCT_135
ACCT_140
ACCT_142
ACCT_143
ACCT_144
ACCT_210
ACCT_230
ACCT_250
ACCT_260
ACCT_270
ACCT_280
ACCT_290
ACCT_305
ACCT_310
ACCT_314
ACCT_315
ACCT_320
ACCT_360
ACCT_370
ACCT_381
ACCT_384
ACCT_385
ACCT_389
ACCT_391
ACCT_393
ACCT_395
ACCT_396
ACCT_397
ACCT_399
ACCT_420
ACCT_430
ACCT_440
ACCT_451
ACCT_452
ACCT_453
ACCT_454
ACCT_455
ACCT_458
ACCT_460
ACCT_463
ACCT_475
ACCT_481
ACCT_482
ACCT_532
ACCT_547
ACCT_548
ACCT_549
ACCT_553
ACCT_554
ACCT_555
ACCT_560
ACCT_561
ACCT_564A
ACCT_564B
ACCT_593
ACCT_594
ACCT_595
ACCT_596
ACCT_599
ACCT_002
ACCT_115
ACCT_116
ACCT_117
ACCT_350
ACCT_565
Acct_661A
Acct_769A
Acct_769B
Acct_820A
Acct_954
Acct_925A
Acct_925B1
Acct_925B2
Acct_010A
Acct_010B
Acct_010C
Acct_730A
Acct_730B
Acct_730C
Acct_799I
Acct_814A
Acct_889A
Acct_889B
Acct_892A
Acct_892B
Acct_945A
Acct_945B
Acct_996
Acct_997
Acct_998
Acct_999
ACCT_779A
ACCT_785A
ACCT_798A
ACCT_814B
ACCT_865A
ACCT_900A
ACCT_900B
ACCT_900C
ACCT_900D
ACCT_900F
ACCT_903
ACCT_904
ACCT_905
ACCT_906
ACCT_961A
ACCT_972A
ACCT_972B
ACCT_972C
ACCT_972D
ACCT_972E
ACCT_973A
ACCT_973B
ACCT_976B
ACCT_982A
ACCT_982B
ACCT_982C
ACCT_982D
ACCT_982E
ACCT_983A
ACCT_983B
ACCT_986B
ACCT_617A
ACCT_618A
ACCT_718A
ACCT_617B
ACCT_617C
ACCT_618B
ACCT_618C
ACCT_883A
ACCT_883B1
ACCT_883B2
ACCT_883C
ACCT_881
ACCT_882
ACCT_822
ACCT_567
ACCT_568
ACCT_020C
ACCT_021C
ACCT_022C
ACCT_023C
ACCT_041C
ACCT_020D
ACCT_021D
ACCT_022D
ACCT_023D
ACCT_041D
ACCT_713A
ACCT_714A
ACCT_715A
ACCT_716A
ACCT_020E
ACCT_021E
ACCT_022E
ACCT_023E
ACCT_041E
ACCT_020F
ACCT_021F
ACCT_022F
ACCT_023F
ACCT_041F
ACCT_065A
ACCT_065B
ACCT_065C
ACCT_065D
ACCT_065E
ACCT_067A
ACCT_067B
ACCT_067C
ACCT_550J
ACCT_550K
ACCT_550L
ACCT_551J
ACCT_551K
ACCT_551L
ACCT_029A
ACCT_029B
ACCT_029C
ACCT_029D
ACCT_029E
ACCT_030A
ACCT_030B
ACCT_030C
ACCT_030D
ACCT_030E
ACCT_032A
ACCT_032B
ACCT_032C
ACCT_032D
ACCT_032E
ACCT_704F1
ACCT_704F2
ACCT_704F3
ACCT_704F4
ACCT_811B
ACCT_PP0027
ACCT_PP0029
ACCT_PP0031
CEO
Fax
Phone
Preparer
President
Principal
ACCT_876
ACCT_830A
ACCT_830B
ACCT_830C
ACCT_830D
ACCT_830E
ACCT_830F
ACCT_830G
ACCT_830H
ACCT_830I
ACCT_830J
CEO_F
CEO_M
Preparer_F
Preparer_M
President_F
President_M
Principal_F
Principal_M
Acct_891
ACCT_893
ACCT_894
Acct_700
Acct_701
Acct_886A
Acct_886B
Acct_886C
Acct_886D
Acct_886E
Acct_886F
Acct_886G
Acct_887A
Acct_887B
Acct_887C
Acct_887D
Acct_887E
Acct_887F
Acct_887G
Acct_887H
Acct_887I
Acct_887J
Acct_887K
Acct_887L
Acct_889
Acct_711
Acct_887M
Acct_887N
Acct_887P
Acct_887Z
Acct_842
Acct_843
ACCT_830K
ACCT_830L
ACCT_830M
ACCT_830N
ACCT_830O
ACCT_830P
ACCT_830Q
ACCT_830R
ACCT_830S
ACCT_830T
ACCT_566A
CertifiedBy
CertifiedBy_F
CertifiedBy_M
Acct_879A
Acct_879B
Acct_879C
Acct_879D
Acct_879E
Acct_879F
Acct_879G
Acct_879H
Acct_879I
Acct_879J
Acct_879K
Acct_879L
Acct_879M
Acct_879N
Acct_879O
Acct_879P
Acct_879Q
Acct_879R
Acct_879S
Acct_879T
Acct_888
Extension
Acct_834A1
Acct_834B1
Acct_834C1
Acct_834D1
Acct_834E1
Acct_834F1
Acct_834G1
Acct_834H1
Acct_834I1
Acct_834J1
Acct_834K1
Acct_834L1
Acct_834M1
Acct_834N1
Acct_834O1
Acct_834P1
Acct_834Q1
Acct_834R1
Acct_834S1
Acct_834T1
Acct_566B
Acct_887R
ACCT_879A1
ACCT_879A2
ACCT_879A3
ACCT_879A4
ACCT_879A5
ACCT_879B1
ACCT_879B2
ACCT_879B3
ACCT_879B4
ACCT_879B5
ACCT_879C1
ACCT_879C2
ACCT_879C3
ACCT_879C4
ACCT_879D1
ACCT_879D2
ACCT_879D3
ACCT_879D4
ACCT_879D5
ACCT_879D6
ACCT_879D7
ACCT_879D8
ACCT_879U
ACCT_879V
ACCT_879W
ACCT_879X
ACCT_879Y
ACCT_886H
ACCT_887S
ACCT_887T
ACCT_887U
ACCT_845A
ACCT_845B
ACCT_845C
ACCT_845D
ACCT_845E
ACCT_845F
ACCT_845G
ACCT_845H
ACCT_845I
ACCT_845J
ACCT_845K
ACCT_845L
ACCT_845M
ACCT_845N
ACCT_845O
ACCT_845P
ACCT_845Q
ACCT_845R
ACCT_845S
ACCT_845T
ACCT_879D9
Acct_855A
Acct_855B
Acct_855C
Acct_855D
Acct_855E
Acct_855F
Acct_855G
Acct_855H
Acct_855I
Acct_855J
Acct_855K
Acct_855L
Acct_855M
Acct_855N
Acct_855O
Acct_855P
Acct_855Q
Acct_855R
Acct_855S
Acct_855T
BondProvider
MemberMinorityStatus_y
EligibleMinorityStatus_y
MemberAsianAmerican
Acct_887V
Acct_879Q1
Acct_1027Z
Acct_1028Z
Acct_1029Z
ACCT_879B6
ACCT_879B7
ACCT_PI0007
ACCT_PI0008
ACCT_PI0009
ACCT_PP0026
ACCT_PP0028
ACCT_PP0030
ACCT_PP0032
ACCT_PP0033
Acct_879D10
ACCT_PC0013
ACCT_PI0011
ACCT_PI0012
ACCT_PI0013
ACCT_PI0014
ACCT_PI0015
ACCT_PI0016
ACCT_PI0017
ACCT_PI0018
ACCT_PP0034
ACCT_PP0035
ACCT_PP0036
ACCT_PP0058
ACCT_831A
ACCT_831B
ACCT_831C
ACCT_831D
ACCT_831E
ACCT_831F
ACCT_831G
ACCT_831H
ACCT_831I
ACCT_831J
ACCT_832A
ACCT_832B
ACCT_832C
ACCT_832D
ACCT_832E
ACCT_832F
ACCT_832G
ACCT_832H
ACCT_832I
ACCT_832J
ACCT_833A
ACCT_833B
ACCT_833C
ACCT_833D
ACCT_833E
ACCT_833F
ACCT_833G
ACCT_833H
ACCT_833I
ACCT_833J
ACCT_834A
ACCT_834B
ACCT_834C
ACCT_834D
ACCT_834E
ACCT_834F
ACCT_834G
ACCT_834H
ACCT_834I
ACCT_834J
ACCT_835A
ACCT_835B
ACCT_835C
ACCT_835D
ACCT_835E
ACCT_835F
ACCT_835G
ACCT_835H
ACCT_835I
ACCT_835J
ACCT_003
ACCT_064
ACCT_459
ACCT_617
ACCT_618
ACCT_786A
ACCT_786B
ACCT_878A
ACCT_878B
ACCT_878C
ACCT_878D
ACCT_878E
ACCT_878F
ACCT_878G
ACCT_878H
ACCT_878I
ACCT_878J
ACCT_878K
ACCT_878L
ACCT_878M
ACCT_878N
ACCT_831K
ACCT_831L
ACCT_831M
ACCT_831N
ACCT_831O
ACCT_831P
ACCT_831Q
ACCT_831R
ACCT_831S
ACCT_831T
ACCT_832K
ACCT_832L
ACCT_832M
ACCT_832N
ACCT_832O
ACCT_832P
ACCT_832Q
ACCT_832R
ACCT_832S
ACCT_832T
ACCT_833K
ACCT_833L
ACCT_833M
ACCT_833N
ACCT_833O
ACCT_833P
ACCT_833Q
ACCT_833R
ACCT_833S
ACCT_833T
ACCT_834K
ACCT_834L
ACCT_834M
ACCT_834N
ACCT_834O
ACCT_834P
ACCT_834Q
ACCT_834R
ACCT_834S
ACCT_834T
ACCT_835K
ACCT_835L
ACCT_835M
ACCT_835N
ACCT_835O
ACCT_835P
ACCT_835Q
ACCT_835R
ACCT_835S
ACCT_835T
ACCT_125F
ACCT_125G
ACCT_125H
ACCT_125I
ACCT_125J
ACCT_126F
ACCT_126G
ACCT_126H
ACCT_126I
ACCT_126J
ACCT_566
ACCT_619
ACCT_691A
ACCT_690
ACCT_690A
ACCT_691
ACCT_619A
ACCT_730B1
ACCT_730B2
ACCT_779
ACCT_836A
ACCT_836B
ACCT_836C
ACCT_836D
ACCT_836E
ACCT_836F
ACCT_836G
ACCT_836H
ACCT_836I
ACCT_836J
ACCT_836K
ACCT_836L
ACCT_836M
ACCT_836N
ACCT_836O
ACCT_836P
ACCT_836Q
ACCT_836R
ACCT_836S
ACCT_836T
ACCT_999A
ACCT_788
ACCT_878O
ACCT_837A
ACCT_837B
ACCT_837C
ACCT_837D
ACCT_837E
ACCT_837F
ACCT_837G
ACCT_837H
ACCT_837I
ACCT_837J
ACCT_837K
ACCT_837L
ACCT_837M
ACCT_837N
ACCT_837O
ACCT_837P
ACCT_837Q
ACCT_837R
ACCT_837S
ACCT_837T
ACCT_020G
ACCT_021G
ACCT_022G
ACCT_023G
ACCT_041G
ACCT_020H
ACCT_021H
ACCT_022H
ACCT_023H
ACCT_041H
ACCT_550C
ACCT_551C
ACCT_550D
ACCT_551D
ACCT_550E
ACCT_551E
ACCT_550F
ACCT_551F
ACCT_550G
ACCT_551G
ACCT_550H
ACCT_551H
ACCT_818A
ACCT_631
ACCT_632
ACCT_633
ACCT_634
ACCT_635
ACCT_636
ACCT_637
ACCT_638
ACCT_639
ACCT_641
ACCT_1000A
ACCT_1000B
ACCT_1000C
ACCT_1001A
ACCT_1001B
ACCT_1001C
ACCT_1002A
ACCT_1002B
ACCT_1002C
ACCT_036A
ACCT_036B
ACCT_036C
ACCT_036D
ACCT_036E
ACCT_037A
ACCT_037B
ACCT_037C
ACCT_037D
ACCT_037E
ACCT_038A
ACCT_038B
ACCT_038C
ACCT_038D
ACCT_038E
ACCT_039A
ACCT_039B
ACCT_039C
ACCT_039D
ACCT_039E
ACCT_642

In [48]:
filtered_names.head(40)

,Account,AcctName,AcctDesc,TableName,Annualize,CBSAccount,FPRAccount,STATAcctMain,STATAcctState,STATAcctGraph,STATAcctTable8,STATUS
13,Acct_010,TOTAL ASSETS,TOTAL ASSETS,FS220,False,True,True,True,True,True,True,True
190,Acct_025A,Total number of Loans and Leases,Total number of Loans and Leases,FS220,False,False,True,True,True,False,True,True
192,Acct_025B,Total amount of Loans and Leases,Total amount of Loans and Leases,FS220,True,True,True,True,True,True,True,True
210,Acct_031A,Loans Granted Year-to-Date,Include all loans of all types granted (includ...,FS220,True,False,False,True,False,False,False,True
211,Acct_031B,Amount of Loans Granted Year-to-Date,Include all loans of all types granted (includ...,FS220,True,True,True,True,True,False,True,True
511,Acct_083,Number of current members (not number of accou...,Report the number of credit union members. Rep...,FS220,False,True,True,True,True,True,True,True
512,Acct_084,Number of potential members,Report the number of potential credit union me...,FS220,False,True,True,True,True,False,True,True
564,Acct_100,Total Gross Income,Sum of Operating Income.,FS220,True,True,True,True,True,True,True,False
1083,Acct_115,Total Interest Income,Total Interest Income,FS220A,True,False,False,False,False,False,False,True
1087,Acct_120,Income from Investments (Including Interest an...,"(Including Interest, Dividends and CUSO Income...",FS220A,True,True,True,True,True,False,True,True
1088,Acct_124,Trading Profits and Losses (Realized and Unrea...,"Report gains and losses on trading accounts, b...",FS220A,True,True,True,True,True,False,True,False
1117,Acct_131,Fee Income,Fees charged to members for services or member...,FS220A,True,True,True,True,True,False,True,True
1237,Acct_457,Non-Member Deposits,Report the number of all non-member deposits.,FS220,False,False,False,True,False,False,False,True
1389,Acct_564A,Number of credit union employees who are Full-...,Report the number of credit union employees wh...,FS220A,False,True,True,True,True,False,True,True
1390,Acct_564B,Number of credit union employees who are Part-...,Report the number of credit union employees wh...,FS220A,False,True,True,True,True,False,True,True
1392,Acct_566,Number of credit union branches (include the m...,Number of credit union branches (include the m...,FS220C,False,False,False,False,False,False,False,True
1832,Acct_799I,Total Investments,Total Investments,FS220A,False,False,False,False,False,False,False,False
2599,Acct_997,Total Net Worth,"Sum of Undivided Earnings, Regular Reserves, A...",FS220A,False,False,False,False,True,False,False,True
2600,Acct_998,Net Worth Ratio,Net Worth divided by Total Assets,FS220A,False,False,False,False,False,False,False,True
3344,CurMemAsianAmerican,CurrentMembersAsianAmerican,CurrentMembersAsianAmerican,FS220S,False,True,True,True,True,False,False,True
3345,CurMemBlackAmerican,CurrentMembersBlackAmerican,CurrentMembersBlackAmerican,FS220S,False,True,True,True,True,False,False,True
3346,CurMemHispanicAmerican,CurrentMembersHispanicAmerican,CurrentMembersHispanicAmerican,FS220S,False,True,True,True,True,False,False,True
3347,CurMemMinorityStatus,CurrentMembersMinorityStatus,CurrentMembersMinorityStatus,FS220S,False,True,True,True,True,False,False,True
3348,CurMemNativeAmerican,CurrentMembersNativeAmerican,CurrentMembersNativeAmerican,FS220S,False,True,True,True,True,False,False,True
3349,EligibleAfricanAmerican,Eligible African American,Is Eligible African American,FS220D,False,False,False,False,False,False,False,False
3350,EligibleAsianAmerican,Eligible Asian American,Is Eligible Asian American,FS220D,False,False,False,False,False,False,False,False
3351,EligibleHispanicAmerican,Eligible Hispanic American,Is Eligible Hispanic American,FS220D,False,False,False,False,False,False,False,False
3352,EligibleMinorityStatus,Eligible Minority Status,The Eligible Minority Status,FS220S,False,False,False,False,False,False,False,True
3353,EligibleNativeAmerican,Eligible Native American,Is Eligible Native American,FS220D,False,False,False,False,False,False,False,False
3356,FOMAsianAmerican,FOM Asian American,Eligible Asian American,FS220S,False,True,True,True,True,False,False,True
3357,FOMBlackAmerican,FOM Black American,Eligible Black American,FS220S,False,True,True,True,True,False,False,True
3358,FOMHispanicAmerican,FOM Hispanic American,Eligible Hispanic American,FS220S,False,True,True,True,True,False,False,True
3359,FOMMinorityStatus,Field of Membership Minority Status?,Field of Membership Minority Status?,FS220S,False,True,True,True,True,False,False,True
3360,FOMNativeAmerican,FOM Native American,Eligible Native American,FS220S,False,True,True,True,True,False,False,True
3361,MemberAfricanAmerican,Member African American,Is Member African American,FS220D,False,False,False,False,False,False,False,False
3362,MemberAsianAmerican,Member Asian American,Is Member Asian American,FS220D,False,False,False,False,False,False,False,False
3363,MemberHispanicAmerican,Member Hispanic American,Is Member Hispanic American,FS220D,False,False,False,False,False,False,False,False
3364,MemberMinorityStatus,Member Minority Status,The Member Minority Status,FS220S,False,False,False,False,False,False,False,True
3365,MemberNativeAmerican,Member Native American,Is Member Native American,FS220D,False,False,False,False,False,False,False,False

In [49]:
filtered_names.Account

13                      Acct_010
190                    Acct_025A
192                    Acct_025B
210                    Acct_031A
211                    Acct_031B
511                     Acct_083
512                     Acct_084
564                     Acct_100
1083                    Acct_115
1087                    Acct_120
1088                    Acct_124
1117                    Acct_131
1237                    Acct_457
1389                   Acct_564A
1390                   Acct_564B
1392                    Acct_566
1832                   Acct_799I
2599                    Acct_997
2600                    Acct_998
3344         CurMemAsianAmerican
3345         CurMemBlackAmerican
3346      CurMemHispanicAmerican
3347        CurMemMinorityStatus
3348        CurMemNativeAmerican
3349     EligibleAfricanAmerican
3350       EligibleAsianAmerican
3351    EligibleHispanicAmerican
3352      EligibleMinorityStatus
3353      EligibleNativeAmerican
3356            FOMAsianAmerican
3357            FOMBlackAmerican
3358         FOMHispanicAmerican
3359           FOMMinorityStatus
3360           FOMNativeAmerican
3361       MemberAfricanAmerican
3362         MemberAsianAmerican
3363      MemberHispanicAmerican
3364        MemberMinorityStatus
3365        MemberNativeAmerican
Name: Account, dtype: object

In [50]:
len(filtered_names.Account)

39

In [51]:
# Remap into upper case for consistency
filtered_names["Account_upper"] = filtered_names["Account"].str.upper()

/var/folders/lf/1r0cw2qs3pq870f2x7yb20w40000gn/T/ipykernel_51861/3806518358.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_names["Account_upper"] = filtered_names["Account"].str.upper()

In [52]:
filtered_names.Account_upper

13                      ACCT_010
190                    ACCT_025A
192                    ACCT_025B
210                    ACCT_031A
211                    ACCT_031B
511                     ACCT_083
512                     ACCT_084
564                     ACCT_100
1083                    ACCT_115
1087                    ACCT_120
1088                    ACCT_124
1117                    ACCT_131
1237                    ACCT_457
1389                   ACCT_564A
1390                   ACCT_564B
1392                    ACCT_566
1832                   ACCT_799I
2599                    ACCT_997
2600                    ACCT_998
3344         CURMEMASIANAMERICAN
3345         CURMEMBLACKAMERICAN
3346      CURMEMHISPANICAMERICAN
3347        CURMEMMINORITYSTATUS
3348        CURMEMNATIVEAMERICAN
3349     ELIGIBLEAFRICANAMERICAN
3350       ELIGIBLEASIANAMERICAN
3351    ELIGIBLEHISPANICAMERICAN
3352      ELIGIBLEMINORITYSTATUS
3353      ELIGIBLENATIVEAMERICAN
3356            FOMASIANAMERICAN
3357            FOMBLACKAMERICAN
3358         FOMHISPANICAMERICAN
3359           FOMMINORITYSTATUS
3360           FOMNATIVEAMERICAN
3361       MEMBERAFRICANAMERICAN
3362         MEMBERASIANAMERICAN
3363      MEMBERHISPANICAMERICAN
3364        MEMBERMINORITYSTATUS
3365        MEMBERNATIVEAMERICAN
Name: Account_upper, dtype: object

In [53]:
# create a dictionary mapping from the filtered names DataFrame
column_map = filtered_names.set_index("Account_upper")["AcctName"].dropna().to_dict()

In [54]:
column_map

{'ACCT_010': 'TOTAL ASSETS',
 'ACCT_025A': 'Total number of Loans and Leases',
 'ACCT_025B': 'Total amount of Loans and Leases',
 'ACCT_031A': 'Loans Granted Year-to-Date',
 'ACCT_031B': 'Amount of Loans Granted Year-to-Date',
 'ACCT_083': 'Number of current members (not number of accounts)',
 'ACCT_084': 'Number of potential members',
 'ACCT_100': 'Total Gross Income',
 'ACCT_115': 'Total Interest Income',
 'ACCT_120': 'Income from Investments (Including Interest and Dividends)',
 'ACCT_124': 'Trading Profits and Losses (Realized and Unrealized Gains/Losses)',
 'ACCT_131': 'Fee Income',
 'ACCT_457': 'Non-Member Deposits',
 'ACCT_564A': 'Number of credit union employees who are Full-Time (26 hours or more)',
 'ACCT_564B': 'Number of credit union employees who are Part-Time (25 hours or less per week)',
 'ACCT_566': 'Number of credit union branches (include the main office if member services are conducted at that location)',
 'ACCT_799I': 'Total Investments',
 'ACCT_997': 'Total Net Worth',
 'ACCT_998': 'Net Worth Ratio',
 'CURMEMASIANAMERICAN': 'CurrentMembersAsianAmerican',
 'CURMEMBLACKAMERICAN': 'CurrentMembersBlackAmerican',
 'CURMEMHISPANICAMERICAN': 'CurrentMembersHispanicAmerican',
 'CURMEMMINORITYSTATUS': 'CurrentMembersMinorityStatus',
 'CURMEMNATIVEAMERICAN': 'CurrentMembersNativeAmerican',
 'ELIGIBLEAFRICANAMERICAN': 'Eligible African American',
 'ELIGIBLEASIANAMERICAN': 'Eligible Asian American',
 'ELIGIBLEHISPANICAMERICAN': 'Eligible Hispanic American',
 'ELIGIBLEMINORITYSTATUS': 'Eligible Minority Status',
 'ELIGIBLENATIVEAMERICAN': 'Eligible Native American',
 'FOMASIANAMERICAN': 'FOM Asian American',
 'FOMBLACKAMERICAN': 'FOM Black American',
 'FOMHISPANICAMERICAN': 'FOM Hispanic American',
 'FOMMINORITYSTATUS': 'Field of Membership Minority Status?',
 'FOMNATIVEAMERICAN': 'FOM Native American',
 'MEMBERAFRICANAMERICAN': 'Member African American',
 'MEMBERASIANAMERICAN': 'Member Asian American',
 'MEMBERHISPANICAMERICAN': 'Member Hispanic American',
 'MEMBERMINORITYSTATUS': 'Member Minority Status',
 'MEMBERNATIVEAMERICAN': 'Member Native American'}

In [55]:
len(column_map)

39

In [56]:
for i in merged_fs220.columns:
    print(i)

CU_NUMBER
CYCLE_DATE
JOIN_NUMBER
UPDATE_DATE
ACCT_007
ACCT_008
ACCT_009
ACCT_010
ACCT_011C
ACCT_013
ACCT_018
ACCT_019
ACCT_021B
ACCT_022B
ACCT_023B
ACCT_025A
ACCT_025B
ACCT_031A
ACCT_031B
ACCT_041B
ACCT_042
ACCT_058C
ACCT_065
ACCT_067
ACCT_068
ACCT_069
ACCT_080
ACCT_083
ACCT_084
ACCT_100
ACCT_300
ACCT_340
ACCT_380
ACCT_386
ACCT_387
ACCT_388
ACCT_392
ACCT_400
ACCT_457
ACCT_521
ACCT_522
ACCT_523
ACCT_524
ACCT_550
ACCT_551
ACCT_552
ACCT_562
ACCT_563
ACCT_602
ACCT_630
ACCT_652A
ACCT_652B1
ACCT_652B2
ACCT_655A
ACCT_655B1
ACCT_655B2
ACCT_656C
ACCT_657
ACCT_658
ACCT_662
ACCT_668
ACCT_671
ACCT_672A
ACCT_672B1
ACCT_672B2
ACCT_703
ACCT_704
ACCT_705
ACCT_706
ACCT_707
ACCT_708
ACCT_710
ACCT_712
ACCT_713
ACCT_714
ACCT_715
ACCT_716
ACCT_718
ACCT_719
ACCT_720
ACCT_721
ACCT_722
ACCT_723
ACCT_724
ACCT_730
ACCT_741A
ACCT_741B1
ACCT_741B2
ACCT_742A
ACCT_742B1
ACCT_742B2
ACCT_746A
ACCT_746B1
ACCT_746B2
ACCT_749
ACCT_750A
ACCT_750B1
ACCT_750B2
ACCT_751
ACCT_755
ACCT_760C
ACCT_761C
ACCT_771
ACCT_775
ACCT_794
ACCT_798
ACCT_799A
ACCT_799B1
ACCT_799B2
ACCT_825
ACCT_860C
ACCT_880
ACCT_902
ACCT_906A
ACCT_908A
ACCT_908C
ACCT_911
ACCT_931
ACCT_940
ACCT_959
ACCT_960
ACCT_968
ACCT_973
ACCT_975
ACCT_976
ACCT_991
Acct_965A
Acct_965B
Acct_965C
Acct_965D
ACCT_020A
ACCT_020B
ACCT_024A
ACCT_024B
ACCT_042A
ACCT_090A
ACCT_090B
ACCT_090C
ACCT_090D
ACCT_099A
ACCT_143A
ACCT_143B
ACCT_143C
ACCT_143D
ACCT_400A
ACCT_400B
ACCT_400C
ACCT_400D
ACCT_400F
ACCT_459A
ACCT_463A
ACCT_475A
ACCT_475B
ACCT_475C
ACCT_475D
ACCT_691B
ACCT_691C
ACCT_692
ACCT_692A
ACCT_704A
ACCT_704B
ACCT_704C
ACCT_704D
ACCT_704E
ACCT_705A
ACCT_705B
ACCT_708B
ACCT_720A
ACCT_720B
ACCT_720C
ACCT_720D
ACCT_720E
ACCT_721A
ACCT_721B
ACCT_724B
ACCT_733A
ACCT_745C1
ACCT_745C2
ACCT_796C1
ACCT_796C2
ACCT_797C1
ACCT_797C2
ACCT_799C1
ACCT_799C2
ACCT_965C1
ACCT_965C2
ACCT_088
ACCT_799A1
ACCT_672B
ACCT_672C1
ACCT_672C2
ACCT_672D
ACCT_744B
ACCT_744C1
ACCT_744C2
ACCT_744D
ACCT_652B
ACCT_652C1
ACCT_652C2
ACCT_652D
ACCT_766A
ACCT_766B
ACCT_766C1
ACCT_766C2
ACCT_766D
ACCT_766E
ACCT_798A1
ACCT_798A2
ACCT_798A3
ACCT_009A
ACCT_009B
ACCT_009C
ACCT_769A1
ACCT_769B1
ACCT_616
ACCT_616A
ACCT_704A1
ACCT_704C1
ACCT_980
ACCT_742C1
ACCT_742C2
ACCT_020J
ACCT_020K
ACCT_020L
ACCT_021J
ACCT_021K
ACCT_021L
ACCT_022J
ACCT_022K
ACCT_022L
ACCT_023J
ACCT_023K
ACCT_023L
ACCT_041J
ACCT_041K
ACCT_041L
Acct_1019
Acct_1019A
Acct_1019B
Acct_1019C
Acct_1019D
Acct_1019E
Acct_789A
Acct_789A1
Acct_789B
Acct_789B1
ACCT_PG0001
ACCT_PP0037
ACCT_PP0038
ACCT_PP0039
ACCT_PP0040
ACCT_PP0041
ACCT_PP0042
ACCT_PP0043
ACCT_PP0044
ACCT_PP0045
ACCT_PP0046
ACCT_PP0047
ACCT_PP0048
ACCT_PR0001
ACCT_PR0002
ACCT_PR0003
ACCT_PR0004
BoardAsianAmerican
BoardBlackAmerican
BoardHispanicAmerican
BoardMinorityStatus
BoardNativeAmerican
CurMemAsianAmerican
CurMemBlackAmerican
CurMemHispanicAmerican
CurMemMinorityStatus
CurMemNativeAmerican
EligibleMinorityStatus_x
FOMAsianAmerican
FOMBlackAmerican
FOMHispanicAmerican
FOMMinorityStatus
FOMNativeAmerican
MemberMinorityStatus_x
ACCT_001
ACCT_011A
ACCT_011B1
ACCT_011B2
ACCT_013A
ACCT_013B1
ACCT_013B2
ACCT_014
ACCT_017
ACCT_018A
ACCT_018B1
ACCT_018B2
ACCT_021A
ACCT_022A
ACCT_023A
ACCT_041A
ACCT_058A
ACCT_058B1
ACCT_058B2
ACCT_062
ACCT_063
ACCT_076
ACCT_077
ACCT_078
ACCT_079
ACCT_081
ACCT_082
ACCT_090
ACCT_099
ACCT_110
ACCT_119
ACCT_120
ACCT_124
ACCT_125A
ACCT_125B
ACCT_125C
ACCT_125D
ACCT_125E
ACCT_126A
ACCT_126B
ACCT_126C
ACCT_126D
ACCT_126E
ACCT_131
ACCT_132
ACCT_133
ACCT_134
ACCT_135
ACCT_140
ACCT_142
ACCT_143
ACCT_144
ACCT_210
ACCT_230
ACCT_250
ACCT_260
ACCT_270
ACCT_280
ACCT_290
ACCT_305
ACCT_310
ACCT_314
ACCT_315
ACCT_320
ACCT_360
ACCT_370
ACCT_381
ACCT_384
ACCT_385
ACCT_389
ACCT_391
ACCT_393
ACCT_395
ACCT_396
ACCT_397
ACCT_399
ACCT_420
ACCT_430
ACCT_440
ACCT_451
ACCT_452
ACCT_453
ACCT_454
ACCT_455
ACCT_458
ACCT_460
ACCT_463
ACCT_475
ACCT_481
ACCT_482
ACCT_532
ACCT_547
ACCT_548
ACCT_549
ACCT_553
ACCT_554
ACCT_555
ACCT_560
ACCT_561
ACCT_564A
ACCT_564B
ACCT_593
ACCT_594
ACCT_595
ACCT_596
ACCT_599
ACCT_002
ACCT_115
ACCT_116
ACCT_117
ACCT_350
ACCT_565
Acct_661A
Acct_769A
Acct_769B
Acct_820A
Acct_954
Acct_925A
Acct_925B1
Acct_925B2
Acct_010A
Acct_010B
Acct_010C
Acct_730A
Acct_730B
Acct_730C
Acct_799I
Acct_814A
Acct_889A
Acct_889B
Acct_892A
Acct_892B
Acct_945A
Acct_945B
Acct_996
Acct_997
Acct_998
Acct_999
ACCT_779A
ACCT_785A
ACCT_798A
ACCT_814B
ACCT_865A
ACCT_900A
ACCT_900B
ACCT_900C
ACCT_900D
ACCT_900F
ACCT_903
ACCT_904
ACCT_905
ACCT_906
ACCT_961A
ACCT_972A
ACCT_972B
ACCT_972C
ACCT_972D
ACCT_972E
ACCT_973A
ACCT_973B
ACCT_976B
ACCT_982A
ACCT_982B
ACCT_982C
ACCT_982D
ACCT_982E
ACCT_983A
ACCT_983B
ACCT_986B
ACCT_617A
ACCT_618A
ACCT_718A
ACCT_617B
ACCT_617C
ACCT_618B
ACCT_618C
ACCT_883A
ACCT_883B1
ACCT_883B2
ACCT_883C
ACCT_881
ACCT_882
ACCT_822
ACCT_567
ACCT_568
ACCT_020C
ACCT_021C
ACCT_022C
ACCT_023C
ACCT_041C
ACCT_020D
ACCT_021D
ACCT_022D
ACCT_023D
ACCT_041D
ACCT_713A
ACCT_714A
ACCT_715A
ACCT_716A
ACCT_020E
ACCT_021E
ACCT_022E
ACCT_023E
ACCT_041E
ACCT_020F
ACCT_021F
ACCT_022F
ACCT_023F
ACCT_041F
ACCT_065A
ACCT_065B
ACCT_065C
ACCT_065D
ACCT_065E
ACCT_067A
ACCT_067B
ACCT_067C
ACCT_550J
ACCT_550K
ACCT_550L
ACCT_551J
ACCT_551K
ACCT_551L
ACCT_029A
ACCT_029B
ACCT_029C
ACCT_029D
ACCT_029E
ACCT_030A
ACCT_030B
ACCT_030C
ACCT_030D
ACCT_030E
ACCT_032A
ACCT_032B
ACCT_032C
ACCT_032D
ACCT_032E
ACCT_704F1
ACCT_704F2
ACCT_704F3
ACCT_704F4
ACCT_811B
ACCT_PP0027
ACCT_PP0029
ACCT_PP0031
CEO
Fax
Phone
Preparer
President
Principal
ACCT_876
ACCT_830A
ACCT_830B
ACCT_830C
ACCT_830D
ACCT_830E
ACCT_830F
ACCT_830G
ACCT_830H
ACCT_830I
ACCT_830J
CEO_F
CEO_M
Preparer_F
Preparer_M
President_F
President_M
Principal_F
Principal_M
Acct_891
ACCT_893
ACCT_894
Acct_700
Acct_701
Acct_886A
Acct_886B
Acct_886C
Acct_886D
Acct_886E
Acct_886F
Acct_886G
Acct_887A
Acct_887B
Acct_887C
Acct_887D
Acct_887E
Acct_887F
Acct_887G
Acct_887H
Acct_887I
Acct_887J
Acct_887K
Acct_887L
Acct_889
Acct_711
Acct_887M
Acct_887N
Acct_887P
Acct_887Z
Acct_842
Acct_843
ACCT_830K
ACCT_830L
ACCT_830M
ACCT_830N
ACCT_830O
ACCT_830P
ACCT_830Q
ACCT_830R
ACCT_830S
ACCT_830T
ACCT_566A
CertifiedBy
CertifiedBy_F
CertifiedBy_M
Acct_879A
Acct_879B
Acct_879C
Acct_879D
Acct_879E
Acct_879F
Acct_879G
Acct_879H
Acct_879I
Acct_879J
Acct_879K
Acct_879L
Acct_879M
Acct_879N
Acct_879O
Acct_879P
Acct_879Q
Acct_879R
Acct_879S
Acct_879T
Acct_888
Extension
Acct_834A1
Acct_834B1
Acct_834C1
Acct_834D1
Acct_834E1
Acct_834F1
Acct_834G1
Acct_834H1
Acct_834I1
Acct_834J1
Acct_834K1
Acct_834L1
Acct_834M1
Acct_834N1
Acct_834O1
Acct_834P1
Acct_834Q1
Acct_834R1
Acct_834S1
Acct_834T1
Acct_566B
Acct_887R
ACCT_879A1
ACCT_879A2
ACCT_879A3
ACCT_879A4
ACCT_879A5
ACCT_879B1
ACCT_879B2
ACCT_879B3
ACCT_879B4
ACCT_879B5
ACCT_879C1
ACCT_879C2
ACCT_879C3
ACCT_879C4
ACCT_879D1
ACCT_879D2
ACCT_879D3
ACCT_879D4
ACCT_879D5
ACCT_879D6
ACCT_879D7
ACCT_879D8
ACCT_879U
ACCT_879V
ACCT_879W
ACCT_879X
ACCT_879Y
ACCT_886H
ACCT_887S
ACCT_887T
ACCT_887U
ACCT_845A
ACCT_845B
ACCT_845C
ACCT_845D
ACCT_845E
ACCT_845F
ACCT_845G
ACCT_845H
ACCT_845I
ACCT_845J
ACCT_845K
ACCT_845L
ACCT_845M
ACCT_845N
ACCT_845O
ACCT_845P
ACCT_845Q
ACCT_845R
ACCT_845S
ACCT_845T
ACCT_879D9
Acct_855A
Acct_855B
Acct_855C
Acct_855D
Acct_855E
Acct_855F
Acct_855G
Acct_855H
Acct_855I
Acct_855J
Acct_855K
Acct_855L
Acct_855M
Acct_855N
Acct_855O
Acct_855P
Acct_855Q
Acct_855R
Acct_855S
Acct_855T
BondProvider
MemberMinorityStatus_y
EligibleMinorityStatus_y
MemberAsianAmerican
Acct_887V
Acct_879Q1
Acct_1027Z
Acct_1028Z
Acct_1029Z
ACCT_879B6
ACCT_879B7
ACCT_PI0007
ACCT_PI0008
ACCT_PI0009
ACCT_PP0026
ACCT_PP0028
ACCT_PP0030
ACCT_PP0032
ACCT_PP0033
Acct_879D10
ACCT_PC0013
ACCT_PI0011
ACCT_PI0012
ACCT_PI0013
ACCT_PI0014
ACCT_PI0015
ACCT_PI0016
ACCT_PI0017
ACCT_PI0018
ACCT_PP0034
ACCT_PP0035
ACCT_PP0036
ACCT_PP0058
ACCT_831A
ACCT_831B
ACCT_831C
ACCT_831D
ACCT_831E
ACCT_831F
ACCT_831G
ACCT_831H
ACCT_831I
ACCT_831J
ACCT_832A
ACCT_832B
ACCT_832C
ACCT_832D
ACCT_832E
ACCT_832F
ACCT_832G
ACCT_832H
ACCT_832I
ACCT_832J
ACCT_833A
ACCT_833B
ACCT_833C
ACCT_833D
ACCT_833E
ACCT_833F
ACCT_833G
ACCT_833H
ACCT_833I
ACCT_833J
ACCT_834A
ACCT_834B
ACCT_834C
ACCT_834D
ACCT_834E
ACCT_834F
ACCT_834G
ACCT_834H
ACCT_834I
ACCT_834J
ACCT_835A
ACCT_835B
ACCT_835C
ACCT_835D
ACCT_835E
ACCT_835F
ACCT_835G
ACCT_835H
ACCT_835I
ACCT_835J
ACCT_003
ACCT_064
ACCT_459
ACCT_617
ACCT_618
ACCT_786A
ACCT_786B
ACCT_878A
ACCT_878B
ACCT_878C
ACCT_878D
ACCT_878E
ACCT_878F
ACCT_878G
ACCT_878H
ACCT_878I
ACCT_878J
ACCT_878K
ACCT_878L
ACCT_878M
ACCT_878N
ACCT_831K
ACCT_831L
ACCT_831M
ACCT_831N
ACCT_831O
ACCT_831P
ACCT_831Q
ACCT_831R
ACCT_831S
ACCT_831T
ACCT_832K
ACCT_832L
ACCT_832M
ACCT_832N
ACCT_832O
ACCT_832P
ACCT_832Q
ACCT_832R
ACCT_832S
ACCT_832T
ACCT_833K
ACCT_833L
ACCT_833M
ACCT_833N
ACCT_833O
ACCT_833P
ACCT_833Q
ACCT_833R
ACCT_833S
ACCT_833T
ACCT_834K
ACCT_834L
ACCT_834M
ACCT_834N
ACCT_834O
ACCT_834P
ACCT_834Q
ACCT_834R
ACCT_834S
ACCT_834T
ACCT_835K
ACCT_835L
ACCT_835M
ACCT_835N
ACCT_835O
ACCT_835P
ACCT_835Q
ACCT_835R
ACCT_835S
ACCT_835T
ACCT_125F
ACCT_125G
ACCT_125H
ACCT_125I
ACCT_125J
ACCT_126F
ACCT_126G
ACCT_126H
ACCT_126I
ACCT_126J
ACCT_566
ACCT_619
ACCT_691A
ACCT_690
ACCT_690A
ACCT_691
ACCT_619A
ACCT_730B1
ACCT_730B2
ACCT_779
ACCT_836A
ACCT_836B
ACCT_836C
ACCT_836D
ACCT_836E
ACCT_836F
ACCT_836G
ACCT_836H
ACCT_836I
ACCT_836J
ACCT_836K
ACCT_836L
ACCT_836M
ACCT_836N
ACCT_836O
ACCT_836P
ACCT_836Q
ACCT_836R
ACCT_836S
ACCT_836T
ACCT_999A
ACCT_788
ACCT_878O
ACCT_837A
ACCT_837B
ACCT_837C
ACCT_837D
ACCT_837E
ACCT_837F
ACCT_837G
ACCT_837H
ACCT_837I
ACCT_837J
ACCT_837K
ACCT_837L
ACCT_837M
ACCT_837N
ACCT_837O
ACCT_837P
ACCT_837Q
ACCT_837R
ACCT_837S
ACCT_837T
ACCT_020G
ACCT_021G
ACCT_022G
ACCT_023G
ACCT_041G
ACCT_020H
ACCT_021H
ACCT_022H
ACCT_023H
ACCT_041H
ACCT_550C
ACCT_551C
ACCT_550D
ACCT_551D
ACCT_550E
ACCT_551E
ACCT_550F
ACCT_551F
ACCT_550G
ACCT_551G
ACCT_550H
ACCT_551H
ACCT_818A
ACCT_631
ACCT_632
ACCT_633
ACCT_634
ACCT_635
ACCT_636
ACCT_637
ACCT_638
ACCT_639
ACCT_641
ACCT_1000A
ACCT_1000B
ACCT_1000C
ACCT_1001A
ACCT_1001B
ACCT_1001C
ACCT_1002A
ACCT_1002B
ACCT_1002C
ACCT_036A
ACCT_036B
ACCT_036C
ACCT_036D
ACCT_036E
ACCT_037A
ACCT_037B
ACCT_037C
ACCT_037D
ACCT_037E
ACCT_038A
ACCT_038B
ACCT_038C
ACCT_038D
ACCT_038E
ACCT_039A
ACCT_039B
ACCT_039C
ACCT_039D
ACCT_039E
ACCT_642

In [57]:
# fill na values with 0 in MemberMinorityStatus_x column
merged_fs220['MemberMinorityStatus_x'].fillna(0, inplace=True)

(merged_fs220['MemberMinorityStatus_x'] == merged_fs220['MemberMinorityStatus_y']).all()

/var/folders/lf/1r0cw2qs3pq870f2x7yb20w40000gn/T/ipykernel_51861/1482917895.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_fs220['MemberMinorityStatus_x'].fillna(0, inplace=True)

True

In [58]:
merged_fs220['EligibleMinorityStatus_x'].fillna(0, inplace=True)

(merged_fs220['EligibleMinorityStatus_y'] == merged_fs220['EligibleMinorityStatus_x']).all()

/var/folders/lf/1r0cw2qs3pq870f2x7yb20w40000gn/T/ipykernel_51861/3753428305.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_fs220['EligibleMinorityStatus_x'].fillna(0, inplace=True)

True

In [59]:
merged_fs220.drop(columns=['MemberMinorityStatus_y', 'EligibleMinorityStatus_y'], inplace=True)
merged_fs220.rename(columns={
    'MemberMinorityStatus_x': 'MemberMinorityStatus',
    'EligibleMinorityStatus_x': 'EligibleMinorityStatus'
}, inplace=True)

In [60]:
merged_upper = merged_fs220.copy()
merged_upper.columns = [col.upper() for col in merged_upper.columns]

In [61]:
merged_upper.head(3)

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,UPDATE_DATE,ACCT_007,ACCT_008,ACCT_009,ACCT_010,ACCT_011C,ACCT_013,...,ACCT_038B,ACCT_038C,ACCT_038D,ACCT_038E,ACCT_039A,ACCT_039B,ACCT_039C,ACCT_039D,ACCT_039E,ACCT_642
0,1,12/31/2024 0:00:00,2,1/29/2025 10:45:12 PM,41785,5201,0,11835153,0,10456209,...,0,0,0,0,0,0,0,0,0,0
1,6,12/31/2024 0:00:00,7,1/30/2025 10:36:36 PM,2868178,750856,0,269952063,0,204597639,...,0,0,0,0,0,0,0,0,0,0
2,12,12/31/2024 0:00:00,11,1/23/2025 10:14:11 PM,4871838,488776,0,60540924,0,55308291,...,0,0,0,0,0,0,0,0,0,0

In [62]:
matching_cols = [col for col in merged_upper.columns if col in column_map]

In [63]:
print(len(matching_cols))
matching_cols

32

['ACCT_010',
 'ACCT_025A',
 'ACCT_025B',
 'ACCT_031A',
 'ACCT_031B',
 'ACCT_083',
 'ACCT_084',
 'ACCT_100',
 'ACCT_457',
 'CURMEMASIANAMERICAN',
 'CURMEMBLACKAMERICAN',
 'CURMEMHISPANICAMERICAN',
 'CURMEMMINORITYSTATUS',
 'CURMEMNATIVEAMERICAN',
 'ELIGIBLEMINORITYSTATUS',
 'FOMASIANAMERICAN',
 'FOMBLACKAMERICAN',
 'FOMHISPANICAMERICAN',
 'FOMMINORITYSTATUS',
 'FOMNATIVEAMERICAN',
 'MEMBERMINORITYSTATUS',
 'ACCT_120',
 'ACCT_124',
 'ACCT_131',
 'ACCT_564A',
 'ACCT_564B',
 'ACCT_115',
 'ACCT_799I',
 'ACCT_997',
 'ACCT_998',
 'MEMBERASIANAMERICAN',
 'ACCT_566']

In [64]:
#missing_columns = [col for col in column_map if col not in matching_cols]
#print(missing_columns)

In [65]:
#merged_upper = merged_upper.rename(columns=column_map)
#merged_upper

In [66]:
extra_cols = ['CU_NUMBER', 'CYCLE_DATE', 'JOIN_NUMBER']

# Combine keys from the rename dictionary and the extra columns
keep_cols = extra_cols + list(column_map.keys())

# Filter the DataFrame to only these columns that actually exist in merged_upper
existing_cols = [col for col in keep_cols if col in merged_upper.columns]
merged_upper = merged_upper[existing_cols].copy()

# Rename the columns using the dictionary
df_filtered = merged_upper.rename(columns=column_map)

In [67]:
df_filtered.columns

Index(['CU_NUMBER', 'CYCLE_DATE', 'JOIN_NUMBER', 'TOTAL ASSETS',
       'Total number of Loans and Leases', 'Total amount of Loans and Leases',
       'Loans Granted Year-to-Date', 'Amount of Loans Granted Year-to-Date',
       'Number of current members (not number of accounts)',
       'Number of potential members', 'Total Gross Income',
       'Total Interest Income',
       'Income from Investments (Including Interest and Dividends)',
       'Trading Profits and Losses (Realized and Unrealized Gains/Losses)',
       'Fee Income', 'Non-Member Deposits',
       'Number of credit union employees who are Full-Time (26 hours or more)',
       'Number of credit union employees who are Part-Time (25 hours or less per week)',
       'Number of credit union branches (include the main office if member services are conducted at that location)',
       'Total Investments', 'Total Net Worth', 'Net Worth Ratio',
       'CurrentMembersAsianAmerican', 'CurrentMembersBlackAmerican',
       'CurrentMembersHispanicAmerican', 'CurrentMembersMinorityStatus',
       'CurrentMembersNativeAmerican', 'Eligible Minority Status',
       'FOM Asian American', 'FOM Black American', 'FOM Hispanic American',
       'Field of Membership Minority Status?', 'FOM Native American',
       'Member Asian American', 'Member Minority Status'],
      dtype='object')

In [68]:
df_filtered.head(3)

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,TOTAL ASSETS,Total number of Loans and Leases,Total amount of Loans and Leases,Loans Granted Year-to-Date,Amount of Loans Granted Year-to-Date,Number of current members (not number of accounts),Number of potential members,...,CurrentMembersMinorityStatus,CurrentMembersNativeAmerican,Eligible Minority Status,FOM Asian American,FOM Black American,FOM Hispanic American,Field of Membership Minority Status?,FOM Native American,Member Asian American,Member Minority Status
0,1,12/31/2024 0:00:00,2,11835153,786,9163389,469,4090293,1267,2000,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,0.0
1,6,12/31/2024 0:00:00,7,269952063,20820,203270107,5184,70778947,29023,80000,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,0.0
2,12,12/31/2024 0:00:00,11,60540924,9419,32014515,5742,18715418,9040,19040,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,0.0

In [69]:
locations_g

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,SiteId,CU_NAME,SiteName,SiteTypeName,MainOffice,PhysicalAddressLine1,PhysicalAddressLine2,...,DriveThru,Shrd_Serv_Cntr_Net,SiteFunctionName,PhysicalAddressStateName,YEAR_OPENED,TOM_CODE,IsMDI,FullPhysicalAddress,latitudes,longitudes
0,1,12/31/2024 0:00:00,2,45553,MORRIS SHEPPARD TEXARKANA,MORRIS SHEPPARD TEXARKANA FCU,Corporate Office,Yes,419 W 4TH ST,NaN,...,0.0,0.0,NaN,NaN,1934,36,False,"419 W 4TH ST, TEXARKANA, TX, 75501, United States",29.993905,-90.179249
1,6,12/31/2024 0:00:00,7,40302,THE NEW ORLEANS FIREMEN'S,Slidell,Branch Office,No,1512 Gause Blvd,NaN,...,1.0,0.0,NaN,NaN,1934,36,False,"1512 Gause Blvd, Slidell, LA, 70458, United St...",30.284789,-89.757589
2,6,12/31/2024 0:00:00,7,41260,THE NEW ORLEANS FIREMEN'S,Metairie,Corporate Office,Yes,4401 W Napoleon Ave,NaN,...,0.0,0.0,NaN,NaN,1934,36,False,"4401 W Napoleon Ave, Metairie, LA, 70001-2406,...",33.421956,-94.047144
3,6,12/31/2024 0:00:00,7,41353,THE NEW ORLEANS FIREMEN'S,Westbank,Branch Office,No,5163 General DeGaulle Dr Ste F,Suite F,...,0.0,0.0,NaN,NaN,1934,36,False,"5163 General DeGaulle Dr Ste F, Suite F, New O...",29.911799,-90.000273
4,6,12/31/2024 0:00:00,7,41368,THE NEW ORLEANS FIREMEN'S,Mandeville,Branch Office,No,238 Lafitte St,NaN,...,0.0,0.0,NaN,NaN,1934,36,False,"238 Lafitte St, Mandeville, LA, 70448, United ...",30.356082,-90.068717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22982,97113,12/31/2024 0:00:00,8532,51850,"KH CREDIT UNION, INC.",Fort Hamilton Hospital,Other,NaN,630 Eaton Ave,NaN,...,NaN,NaN,ATM,Ohio,1964,99,False,"630 Eaton Ave, Hamilton, OH, 45013, United States",39.633172,-84.204231
22983,97113,12/31/2024 0:00:00,8532,51851,"KH CREDIT UNION, INC.",Beavercreek Soin ATM,Other,NaN,3535 Pentagon Blvd,NaN,...,NaN,NaN,ATM,Ohio,1964,99,False,"3535 Pentagon Blvd, Beavercreek, OH, 45431-170...",39.771893,-84.062738
22984,97113,12/31/2024 0:00:00,8532,51852,"KH CREDIT UNION, INC.",Prestige Plaza ATM,Other,NaN,1 Prestige Plaza Dr,NaN,...,NaN,NaN,ATM,Ohio,1964,99,False,"1 Prestige Plaza Dr, Miamisburg, OH, 45342, Un...",39.696102,-84.190744
22985,97113,12/31/2024 0:00:00,8532,51853,"KH CREDIT UNION, INC.",Cancer Center ATM,Other,NaN,3700 Southern Blvd,NaN,...,NaN,NaN,ATM,Ohio,1964,99,False,"3700 Southern Blvd, Kettering, OH, 45429, Unit...",39.638103,-84.228142
22986,97113,12/31/2024 0:00:00,8532,51854,"KH CREDIT UNION, INC.",Troy ATM,Other,NaN,600 W Main St,NaN,...,NaN,NaN,ATM,Ohio,1964,99,False,"600 W Main St, Troy, OH, 45373, United States",40.042054,-84.208845

In [70]:
df_merged = pd.merge(
    locations_g, 
    df_filtered, 
    on='CU_NUMBER',  # or whatever your common column is
    how='outer',     # keeps all rows from both DataFrames
    suffixes=('', '_dup')  # avoids conflict; duplicate columns get a suffix
)

In [71]:
for col in df_merged.columns:
    if col.endswith('_dup'):
        original_col = col.replace('_dup', '')
        if original_col in df_merged.columns and df_merged[original_col].equals(df_merged[col]):
            df_merged.drop(columns=[col], inplace=True)

In [72]:
df_merged.columns

Index(['CU_NUMBER', 'CYCLE_DATE', 'JOIN_NUMBER', 'SiteId', 'CU_NAME',
       'SiteName', 'SiteTypeName', 'MainOffice', 'PhysicalAddressLine1',
       'PhysicalAddressLine2', 'PhysicalAddressCity',
       'PhysicalAddressStateCode', 'PhysicalAddressPostalCode',
       'PhysicalAddressCountyName', 'PhysicalAddressCountry',
       'MailingAddressLine1', 'MailingAddressLine2', 'MailingAddressCity',
       'MailingAddressStateCode', 'MailingAddressStateName',
       'MailingAddressPostalCode', 'PhoneNumber', 'HoursOfOperation',
       'MemberServices', 'ATM', 'DriveThru', 'Shrd_Serv_Cntr_Net',
       'SiteFunctionName', 'PhysicalAddressStateName', 'YEAR_OPENED',
       'TOM_CODE', 'IsMDI', 'FullPhysicalAddress', 'latitudes', 'longitudes',
       'CYCLE_DATE_dup', 'JOIN_NUMBER_dup', 'TOTAL ASSETS',
       'Total number of Loans and Leases', 'Total amount of Loans and Leases',
       'Loans Granted Year-to-Date', 'Amount of Loans Granted Year-to-Date',
       'Number of current members (not number of accounts)',
       'Number of potential members', 'Total Gross Income',
       'Total Interest Income',
       'Income from Investments (Including Interest and Dividends)',
       'Trading Profits and Losses (Realized and Unrealized Gains/Losses)',
       'Fee Income', 'Non-Member Deposits',
       'Number of credit union employees who are Full-Time (26 hours or more)',
       'Number of credit union employees who are Part-Time (25 hours or less per week)',
       'Number of credit union branches (include the main office if member services are conducted at that location)',
       'Total Investments', 'Total Net Worth', 'Net Worth Ratio',
       'CurrentMembersAsianAmerican', 'CurrentMembersBlackAmerican',
       'CurrentMembersHispanicAmerican', 'CurrentMembersMinorityStatus',
       'CurrentMembersNativeAmerican', 'Eligible Minority Status',
       'FOM Asian American', 'FOM Black American', 'FOM Hispanic American',
       'Field of Membership Minority Status?', 'FOM Native American',
       'Member Asian American', 'Member Minority Status'],
      dtype='object')

In [73]:
df_merged.drop_duplicates(inplace=True)

In [74]:
df_merged

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,SiteId,CU_NAME,SiteName,SiteTypeName,MainOffice,PhysicalAddressLine1,PhysicalAddressLine2,...,CurrentMembersMinorityStatus,CurrentMembersNativeAmerican,Eligible Minority Status,FOM Asian American,FOM Black American,FOM Hispanic American,Field of Membership Minority Status?,FOM Native American,Member Asian American,Member Minority Status
0,1,12/31/2024 0:00:00,2.0,45553.0,MORRIS SHEPPARD TEXARKANA,MORRIS SHEPPARD TEXARKANA FCU,Corporate Office,Yes,419 W 4TH ST,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,0.0
1,6,12/31/2024 0:00:00,7.0,40302.0,THE NEW ORLEANS FIREMEN'S,Slidell,Branch Office,No,1512 Gause Blvd,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,0.0
2,6,12/31/2024 0:00:00,7.0,41260.0,THE NEW ORLEANS FIREMEN'S,Metairie,Corporate Office,Yes,4401 W Napoleon Ave,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,0.0
3,6,12/31/2024 0:00:00,7.0,41353.0,THE NEW ORLEANS FIREMEN'S,Westbank,Branch Office,No,5163 General DeGaulle Dr Ste F,Suite F,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,0.0
4,6,12/31/2024 0:00:00,7.0,41368.0,THE NEW ORLEANS FIREMEN'S,Mandeville,Branch Office,No,238 Lafitte St,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22987,97113,12/31/2024 0:00:00,8532.0,51850.0,"KH CREDIT UNION, INC.",Fort Hamilton Hospital,Other,NaN,630 Eaton Ave,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,0.0
22988,97113,12/31/2024 0:00:00,8532.0,51851.0,"KH CREDIT UNION, INC.",Beavercreek Soin ATM,Other,NaN,3535 Pentagon Blvd,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,0.0
22989,97113,12/31/2024 0:00:00,8532.0,51852.0,"KH CREDIT UNION, INC.",Prestige Plaza ATM,Other,NaN,1 Prestige Plaza Dr,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,0.0
22990,97113,12/31/2024 0:00:00,8532.0,51853.0,"KH CREDIT UNION, INC.",Cancer Center ATM,Other,NaN,3700 Southern Blvd,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,0.0
22991,97113,12/31/2024 0:00:00,8532.0,51854.0,"KH CREDIT UNION, INC.",Troy ATM,Other,NaN,600 W Main St,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,0.0

In [75]:
df_merged.to_csv('/Users/artyom/Documents/work/CreditUnions/locations_merged.csv', index=False)

In [79]:
df_merged["Member Minority Status"]

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
22987    0.0
22988    0.0
22989    0.0
22990    0.0
22991    0.0
Name: Member Minority Status, Length: 22992, dtype: float64